-- Database Organisasi: Uni Afrika (AU)
-- Tipe: Regional

INSERT INTO organisasi_internasional (code, name, type) 
VALUES ('AU', 'Uni Afrika (AU)', 'Regional')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO organisasi_membership (organisasi_id, country_id, membership_type) VALUES
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'afrika selatan' OR name_id = 'afrika selatan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'aljazair' OR name_id = 'aljazair'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'angola' OR name_id = 'angola'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'benin' OR name_id = 'benin'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'botswana' OR name_id = 'botswana'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'burkina faso' OR name_id = 'burkina faso'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'burundi' OR name_id = 'burundi'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'chad' OR name_id = 'chad'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'djibouti' OR name_id = 'djibouti'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'eritrea' OR name_id = 'eritrea'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'eswatini' OR name_id = 'eswatini'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'ethiopia' OR name_id = 'ethiopia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'gabon' OR name_id = 'gabon'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'gambia' OR name_id = 'gambia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'ghana' OR name_id = 'ghana'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'guinea' OR name_id = 'guinea'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'kamerun' OR name_id = 'kamerun'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'kenya' OR name_id = 'kenya'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'komoro' OR name_id = 'komoro'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'kongo' OR name_id = 'kongo'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'lesotho' OR name_id = 'lesotho'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'liberia' OR name_id = 'liberia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'libya' OR name_id = 'libya'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'madagaskar' OR name_id = 'madagaskar'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'malawi' OR name_id = 'malawi'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'mali' OR name_id = 'mali'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'maroko' OR name_id = 'maroko'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'mauritania' OR name_id = 'mauritania'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'mauritius' OR name_id = 'mauritius'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'mesir' OR name_id = 'mesir'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'mozambik' OR name_id = 'mozambik'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'namibia' OR name_id = 'namibia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'niger' OR name_id = 'niger'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'nigeria' OR name_id = 'nigeria'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'pantai gading' OR name_id = 'pantai gading'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'republik afrika tengah' OR name_id = 'republik afrika tengah'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'republik demokratik kongo' OR name_id = 'republik demokratik kongo'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'republik sudan' OR name_id = 'republik sudan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'rwanda' OR name_id = 'rwanda'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'sao tome dan principe' OR name_id = 'sao tome dan principe'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'senegal' OR name_id = 'senegal'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'seychelles' OR name_id = 'seychelles'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'sierra leone' OR name_id = 'sierra leone'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'somalia' OR name_id = 'somalia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'sudan selatan' OR name_id = 'sudan selatan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'tanjung verde' OR name_id = 'tanjung verde'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'togo' OR name_id = 'togo'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'AU'), (SELECT id FROM countries WHERE name_en = 'tunisia' OR name_id = 'tunisia'), 'Member');