-- Database Organisasi: Organisasi Kerja Sama Islam (OKI)
-- Tipe: Regional

INSERT INTO organisasi_internasional (code, name, type) 
VALUES ('OKI', 'Organisasi Kerja Sama Islam (OKI)', 'Regional')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO organisasi_membership (organisasi_id, country_id, membership_type) VALUES
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'afganistan' OR name_id = 'afganistan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'aljazair' OR name_id = 'aljazair'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'arab saudi' OR name_id = 'arab saudi'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'azerbaijan' OR name_id = 'azerbaijan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'bahrain' OR name_id = 'bahrain'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'bangladesh' OR name_id = 'bangladesh'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'benin' OR name_id = 'benin'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'brunei' OR name_id = 'brunei'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'burkina faso' OR name_id = 'burkina faso'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'chad' OR name_id = 'chad'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'djibouti' OR name_id = 'djibouti'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'gabon' OR name_id = 'gabon'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'gambia' OR name_id = 'gambia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'guinea' OR name_id = 'guinea'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'guyana' OR name_id = 'guyana'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'indonesia' OR name_id = 'indonesia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'irak' OR name_id = 'irak'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'iran' OR name_id = 'iran'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'kamerun' OR name_id = 'kamerun'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'kazakhstan' OR name_id = 'kazakhstan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'kirgizstan' OR name_id = 'kirgizstan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'komoro' OR name_id = 'komoro'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'kuwait' OR name_id = 'kuwait'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'lebanon' OR name_id = 'lebanon'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'libya' OR name_id = 'libya'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'malaysia' OR name_id = 'malaysia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'mali' OR name_id = 'mali'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'maroko' OR name_id = 'maroko'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'mauritania' OR name_id = 'mauritania'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'mesir' OR name_id = 'mesir'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'mozambik' OR name_id = 'mozambik'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'niger' OR name_id = 'niger'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'nigeria' OR name_id = 'nigeria'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'oman' OR name_id = 'oman'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'pakistan' OR name_id = 'pakistan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'palestina' OR name_id = 'palestina'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'pantai gading' OR name_id = 'pantai gading'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'qatar' OR name_id = 'qatar'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'republik sudan' OR name_id = 'republik sudan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'senegal' OR name_id = 'senegal'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'sierra leone' OR name_id = 'sierra leone'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'somalia' OR name_id = 'somalia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'suriah' OR name_id = 'suriah'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'suriname' OR name_id = 'suriname'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'tajikistan' OR name_id = 'tajikistan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'togo' OR name_id = 'togo'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'tunisia' OR name_id = 'tunisia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'turki' OR name_id = 'turki'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'turkmenistan' OR name_id = 'turkmenistan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'uni emirat arab' OR name_id = 'uni emirat arab'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'uzbekistan' OR name_id = 'uzbekistan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'yaman' OR name_id = 'yaman'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'OKI'), (SELECT id FROM countries WHERE name_en = 'yordania' OR name_id = 'yordania'), 'Member');