export const bahrain_diplomasi = [
  { "no": 1, "mitra": "Afganistan", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 2, "mitra": "Afrika Selatan", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 3, "mitra": "Andorra", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 4, "mitra": "Angola", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 5, "mitra": "Antigua dan Barbuda", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 6, "mitra": "Argentina", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 7, "mitra": "Armenia", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 8, "mitra": "Australia", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 9, "mitra": "Azerbaijan", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 10, "mitra": "Bahama", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 11, "mitra": "Barbados", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 12, "mitra": "Belanda", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 13, "mitra": "Belgia", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 14, "mitra": "Benin", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 15, "mitra": "Bermuda", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 16, "mitra": "Bhutan", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 17, "mitra": "Bolivia", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 18, "mitra": "Botswana", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 19, "mitra": "Brazil", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 20, "mitra": "Brunei", "type": "Kedutaan Besar", "status": "Aktif" }
];
