export const singapura_diplomasi = [
  { "no": 1, "mitra": "Afganistan", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 2, "mitra": "Albania", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 3, "mitra": "Amerika Serikat", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 4, "mitra": "Andorra", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 5, "mitra": "Angola", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 6, "mitra": "Arab Saudi", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 7, "mitra": "Argentina", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 8, "mitra": "Armenia", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 9, "mitra": "Australia", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 10, "mitra": "Austria", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 11, "mitra": "Bahrain", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 12, "mitra": "Bangladesh", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 13, "mitra": "Belanda", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 14, "mitra": "Benin", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 15, "mitra": "Bermuda", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 16, "mitra": "Bolivia", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 17, "mitra": "Botswana", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 18, "mitra": "Brazil", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 19, "mitra": "Brunei", "type": "Kedutaan Besar", "status": "Aktif" }
];
