const fs = require('fs');
const path = require('path');

const projectRoot = 'c:/utama/project/project-sendiri/EM';
const countryPathsFile = path.join(projectRoot, 'apps/src/app/page/map_system/country-paths.json');
const databaseSdaDir = path.join(projectRoot, 'json/database_SDA');

const tableData = [
  { no: 1, name: "afganistan", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 2, name: "afrika selatan", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 3, name: "albania", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 4, name: "aljazair", emas: false, uranium: true, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 5, name: "amerika serikat", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 6, name: "andorra", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 7, name: "angola", emas: true, uranium: true, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 8, name: "antigua dan barbuda", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 9, name: "arab saudi", emas: true, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 10, name: "argentina", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 11, name: "armenia", emas: true, uranium: true, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 12, name: "australia", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 13, name: "austria", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 14, name: "azerbaijan", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 15, name: "bahama", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 16, name: "bahrain", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 17, name: "bangladesh", emas: false, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 18, name: "barbados", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 19, name: "belanda", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 20, name: "belarus", emas: false, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 21, name: "belgia", emas: false, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 22, name: "belize", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 23, name: "benin", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 24, name: "bermuda", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 25, name: "bhutan", emas: false, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 26, name: "bolivia", emas: true, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: false, bijih_besi: true },
  { no: 27, name: "bosnia dan hercegovina", emas: false, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 28, name: "botswana", emas: false, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 29, name: "brazil", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 30, name: "brunei", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 31, name: "bulgaria", emas: false, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 32, name: "burkina faso", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 33, name: "burundi", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 34, name: "ceko", emas: true, uranium: true, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 35, name: "chad", emas: true, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 36, name: "chile", emas: true, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 37, name: "china", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 38, name: "costa rica", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 39, name: "curacao", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 40, name: "denmark", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 41, name: "djibouti", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 42, name: "dominika", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 43, name: "ekuador", emas: true, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 44, name: "el salvador", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 45, name: "eritrea", emas: true, uranium: true, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 46, name: "estonia", emas: false, uranium: true, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 47, name: "eswatini", emas: false, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 48, name: "ethiopia", emas: true, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 49, name: "fiji", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 50, name: "filipina", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 51, name: "finlandia", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: true, logam_tanah_jarang: false, bijih_besi: true },
  { no: 52, name: "gabon", emas: true, uranium: true, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 53, name: "gambia", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 54, name: "georgia", emas: true, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 55, name: "ghana", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 56, name: "gibraltar", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 57, name: "greenland", emas: true, uranium: true, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: true, bijih_besi: true },
  { no: 58, name: "grenada", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 59, name: "guam", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 60, name: "guatemala", emas: true, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 61, name: "guiana prancis", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 62, name: "guinea", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 63, name: "guinea bissau", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 64, name: "guyana", emas: true, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 65, name: "haiti", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 66, name: "honduras", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 67, name: "hong kong", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 68, name: "hungaria", emas: false, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 69, name: "india", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: true, logam_tanah_jarang: false, bijih_besi: true },
  { no: 70, name: "indonesia", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 71, name: "inggris", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 72, name: "irak", emas: false, uranium: true, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 73, name: "iran", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 74, name: "irlandia", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 75, name: "islandia", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 76, name: "israel", emas: false, uranium: true, batu_bara: false, minyak_bumi: false, gas_alam: true, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 77, name: "italia", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 78, name: "jamaika", emas: true, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 79, name: "jepang", emas: true, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 80, name: "jerman", emas: true, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: false, bijih_besi: true },
  { no: 81, name: "kamboja", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 82, name: "kamerun", emas: true, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 83, name: "kanada", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 84, name: "kazakhstan", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 85, name: "kenya", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 86, name: "kepulauan faroe", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 87, name: "kirgizstan", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: true, bijih_besi: true },
  { no: 88, name: "kiribati", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 89, name: "kolombia", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 90, name: "komoro", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 91, name: "kongo", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 92, name: "korea selatan", emas: true, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 93, name: "korea utara", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: true, bijih_besi: true },
  { no: 94, name: "kosovo", emas: false, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 95, name: "kroasia", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 96, name: "kuba", emas: true, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 97, name: "kuwait", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 98, name: "laos", emas: true, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 99, name: "latvia", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 100, name: "lebanon", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 101, name: "lesotho", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 102, name: "liberia", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 103, name: "libya", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 104, name: "liechtenstein", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 105, name: "lithuania", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 106, name: "luksemburg", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 107, name: "madagaskar", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 108, name: "makau", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 109, name: "makedonia utara", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 110, name: "malawi", emas: true, uranium: true, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 111, name: "malaysia", emas: true, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 112, name: "maldives", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 113, name: "mali", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 114, name: "malta", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 115, name: "maroko", emas: true, uranium: true, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 116, name: "marshall", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 117, name: "mauritania", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 118, name: "mauritius", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 119, name: "meksiko", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 120, name: "mesir", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: true, logam_tanah_jarang: false, bijih_besi: true },
  { no: 121, name: "mikronesia", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 122, name: "moldova", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 123, name: "monako", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 124, name: "mongolia", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 125, name: "montenegro", emas: false, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 126, name: "mozambik", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 127, name: "myanmar", emas: true, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 128, name: "namibia", emas: true, uranium: true, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: true, bijih_besi: true },
  { no: 129, name: "nauru", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 130, name: "nepal", emas: false, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 131, name: "niger", emas: true, uranium: true, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 132, name: "nigeria", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: true, logam_tanah_jarang: false, bijih_besi: true },
  { no: 133, name: "nikaragua", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 134, name: "norwegia", emas: true, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 135, name: "oman", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 136, name: "pakistan", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 137, name: "palau", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 138, name: "palestina", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 139, name: "panama", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 140, name: "pantai gading", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 141, name: "papua nugini", emas: true, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 142, name: "paraguay", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 143, name: "peru", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: true, logam_tanah_jarang: false, bijih_besi: true },
  { no: 144, name: "polandia", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 145, name: "portugal", emas: true, uranium: true, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 146, name: "prancis", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 147, name: "puerto rico", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 148, name: "qatar", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 149, name: "republik afrika tengah", emas: true, uranium: true, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 150, name: "republik demokratik kongo", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 151, name: "republik dominika", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 152, name: "republik rumania", emas: true, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 153, name: "republik serbia", emas: true, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 154, name: "republik sudan", emas: true, uranium: true, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 155, name: "republik tanzania", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 156, name: "republik timor leste", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 157, name: "republik uganda", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 158, name: "republik zambia", emas: true, uranium: true, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 159, name: "republik zimbabwe", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 160, name: "rusia", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 161, name: "rwanda", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 162, name: "saint kitts dan nevis", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 163, name: "saint lucia", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 164, name: "saint vincent dan grenadine", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 165, name: "samoa", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 166, name: "samoa amerika", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 167, name: "san marino", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 168, name: "sao tome dan principe", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 169, name: "selandia baru", emas: true, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 170, name: "senegal", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 171, name: "seychelles", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 172, name: "sierra leone", emas: true, uranium: true, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 173, name: "singapura", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 174, name: "siprus", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 175, name: "slovenia", emas: false, uranium: true, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 176, name: "slowakia", emas: false, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 177, name: "somalia", emas: false, uranium: true, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 178, name: "spanyol", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 179, name: "sri lanka", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 180, name: "sudan selatan", emas: true, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 181, name: "suriah", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 182, name: "suriname", emas: true, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 183, name: "swedia", emas: true, uranium: true, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: true, logam_tanah_jarang: false, bijih_besi: true },
  { no: 184, name: "swiss", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 185, name: "tahiti", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 186, name: "taiwan", emas: true, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 187, name: "tajikistan", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 188, name: "tanjung verde", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 189, name: "thailand", emas: true, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 190, name: "togo", emas: true, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 191, name: "tonga", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 192, name: "trinidad dan tobago", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 193, name: "tunisia", emas: true, uranium: true, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 194, name: "turki", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: false, bijih_besi: true },
  { no: 195, name: "turkmenistan", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 196, name: "tuvalu", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 197, name: "ukraina", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 198, name: "uni emirat arab", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 199, name: "uruguay", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 200, name: "uzbekistan", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 201, name: "vanuatu", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 202, name: "vatikan", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: false, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 203, name: "venezuela", emas: true, uranium: false, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: false, litium: true, logam_tanah_jarang: true, bijih_besi: true },
  { no: 204, name: "vietnam", emas: true, uranium: true, batu_bara: true, minyak_bumi: true, gas_alam: true, garam: true, litium: false, logam_tanah_jarang: true, bijih_besi: true },
  { no: 205, name: "yaman", emas: false, uranium: false, batu_bara: false, minyak_bumi: true, gas_alam: true, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: false },
  { no: 206, name: "yordania", emas: false, uranium: false, batu_bara: false, minyak_bumi: false, gas_alam: false, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true },
  { no: 207, name: "yunani", emas: true, uranium: false, batu_bara: true, minyak_bumi: false, gas_alam: false, garam: true, litium: false, logam_tanah_jarang: false, bijih_besi: true }
];

function normalizeName(name) {
  return name.toLowerCase().trim()
    .replace(/[-]/g, '_')
    .replace(/\s+/g, '_')
    .replace(/[^a-z0-9_]/g, '');
}

const fileStr = fs.readFileSync(countryPathsFile, 'utf8').replace(/^\uFEFF/, '');
const countryPaths = JSON.parse(fileStr);

const countryMap = {};
Object.entries(countryPaths).forEach(([displayName, relPath]) => {
  const norm = normalizeName(displayName);
  countryMap[norm] = relPath;
});

const manualMappings = {
  "afganistan": "asia/54_afganistan.ts",
  "afrika_selatan": "afrika/1_afrika_selatan.ts",
  "albania": "eropa/103_albania.ts",
  "aljazair": "afrika/2_aljazair.ts",
  "amerika_serikat": "na/152_amerika_serikat.ts",
  "andorra": "eropa/104_andorra.ts",
  "angola": "afrika/3_angola.ts",
  "antigua_dan_barbuda": "na/153_antigua_dan_barbuda.ts",
  "arab_saudi": "asia/55_arab_saudi.ts",
  "argentina": "sa/195_argentina.ts",
  "armenia": "asia/56_armenia.ts",
  "australia": "oceania/179_australia.ts",
  "austria": "eropa/105_austria.ts",
  "azerbaijan": "asia/57_azerbaijan.ts",
  "bahama": "na/154_bahama.ts",
  "bahrain": "asia/58_bahrain.ts",
  "bangladesh": "asia/59_bangladesh.ts",
  "barbados": "na/155_barbados.ts",
  "belanda": "eropa/106_belanda.ts",
  "belarus": "eropa/107_belarus.ts",
  "belgia": "eropa/108_belgia.ts",
  "belize": "na/156_belize.ts",
  "benin": "afrika/4_benin.ts",
  "bermuda": "na/157_bermuda.ts",
  "bhutan": "asia/60_bhutan.ts",
  "bolivia": "sa/196_bolivia.ts",
  "bosnia_dan_hercegovina": "eropa/109_bosnia_dan_hercegovina.ts",
  "botswana": "afrika/5_botswana.ts",
  "brazil": "sa/197_brazil.ts",
  "brunei": "asia/61_brunei.ts",
  "bulgaria": "eropa/110_bulgaria.ts",
  "burkina_faso": "afrika/6_burkina_faso.ts",
  "burundi": "afrika/7_burundi.ts",
  "ceko": "eropa/111_ceko.ts",
  "chad": "afrika/8_chad.ts",
  "chile": "sa/198_chile.ts",
  "china": "asia/62_china.ts",
  "costa_rica": "na/158_costa_rica.ts",
  "curacao": "na/159_curacao.ts",
  "denmark": "eropa/112_denmark.ts",
  "djibouti": "afrika/9_djibouti.ts",
  "dominika": "na/160_dominika.ts",
  "ekuador": "sa/199_ekuador.ts",
  "el_salvador": "na/161_el_salvador.ts",
  "eritrea": "afrika/10_eritrea.ts",
  "estonia": "eropa/113_estonia.ts",
  "eswatini": "afrika/11_eswatini.ts",
  "ethiopia": "afrika/12_ethiopia.ts",
  "fiji": "oceania/180_fiji.ts",
  "filipina": "asia/63_filipina.ts",
  "finlandia": "eropa/114_finlandia.ts",
  "gabon": "afrika/13_gabon.ts",
  "gambia": "afrika/14_gambia.ts",
  "georgia": "asia/64_georgia.ts",
  "ghana": "afrika/15_ghana.ts",
  "gibraltar": "eropa/115_gibraltar.ts",
  "greenland": "na/162_greenland.ts",
  "grenada": "na/163_grenada.ts",
  "guam": "oceania/181_guam.ts",
  "guatemala": "na/164_guatemala.ts",
  "guiana_prancis": "sa/200_guiana_prancis.ts",
  "guinea": "afrika/16_guinea.ts",
  "guinea_bissau": "afrika/17_guinea_bissau.ts",
  "guyana": "sa/201_guyana.ts",
  "haiti": "na/165_haiti.ts",
  "honduras": "na/166_honduras.ts",
  "hong_kong": "asia/65_hong_kong.ts",
  "hungaria": "eropa/116_hungaria.ts",
  "india": "asia/66_india.ts",
  "indonesia": "asia/67_indonesia.ts",
  "inggris": "eropa/117_inggris.ts",
  "irak": "asia/68_irak.ts",
  "iran": "asia/69_iran.ts",
  "irlandia": "eropa/118_irlandia.ts",
  "islandia": "eropa/119_islandia.ts",
  "israel": "asia/70_israel.ts",
  "italia": "eropa/120_italia.ts",
  "jamaika": "na/167_jamaika.ts",
  "jepang": "asia/71_jepang.ts",
  "jerman": "eropa/121_jerman.ts",
  "kamboja": "asia/72_kamboja.ts",
  "kamerun": "afrika/18_kamerun.ts",
  "kanada": "na/168_kanada.ts",
  "kazakhstan": "asia/73_kazakhstan.ts",
  "kenya": "afrika/19_kenya.ts",
  "kepulauan_faroe": "eropa/122_kepulauan_faroe.ts",
  "kirgizstan": "asia/74_kirgizstan.ts",
  "kiribati": "oceania/182_kiribati.ts",
  "kolombia": "sa/202_kolombia.ts",
  "komoro": "afrika/20_komoro.ts",
  "kongo": "afrika/21_kongo.ts",
  "korea_selatan": "asia/75_korea_selatan.ts",
  "korea_utara": "asia/76_korea_utara.ts",
  "kosovo": "eropa/123_kosovo.ts",
  "kroasia": "eropa/124_kroasia.ts",
  "kuba": "na/169_kuba.ts",
  "kuwait": "asia/77_kuwait.ts",
  "laos": "asia/78_laos.ts",
  "latvia": "eropa/125_latvia.ts",
  "lebanon": "asia/79_lebanon.ts",
  "lesotho": "afrika/22_lesotho.ts",
  "liberia": "afrika/23_liberia.ts",
  "libya": "afrika/24_libya.ts",
  "liechtenstein": "eropa/126_liechtenstein.ts",
  "lithuania": "eropa/127_lithuania.ts",
  "luksemburg": "eropa/128_luksemburg.ts",
  "madagaskar": "afrika/25_madagaskar.ts",
  "makau": "asia/80_makau.ts",
  "makedonia_utara": "eropa/129_makedonia_utara.ts",
  "malawi": "afrika/26_malawi.ts",
  "malaysia": "asia/81_malaysia.ts",
  "maldives": "asia/82_maldives.ts",
  "mali": "afrika/27_mali.ts",
  "malta": "eropa/130_malta.ts",
  "maroko": "afrika/28_maroko.ts",
  "marshall": "oceania/183_marshall.ts",
  "mauritania": "afrika/29_mauritania.ts",
  "mauritius": "afrika/30_mauritius.ts",
  "meksiko": "na/170_meksiko.ts",
  "mesir": "afrika/31_mesir.ts",
  "mikronesia": "oceania/184_mikronesia.ts",
  "moldova": "eropa/131_moldova.ts",
  "monako": "eropa/132_monako.ts",
  "mongolia": "asia/83_mongolia.ts",
  "montenegro": "eropa/133_montenegro.ts",
  "mozambik": "afrika/32_mozambik.ts",
  "myanmar": "asia/84_myanmar.ts",
  "namibia": "afrika/33_namibia.ts",
  "nauru": "oceania/185_nauru.ts",
  "nepal": "asia/85_nepal.ts",
  "niger": "afrika/34_niger.ts",
  "nigeria": "afrika/35_nigeria.ts",
  "nikaragua": "na/171_nikaragua.ts",
  "norwegia": "eropa/134_norwegia.ts",
  "oman": "asia/86_oman.ts",
  "pakistan": "asia/87_pakistan.ts",
  "palau": "oceania/186_palau.ts",
  "palestina": "asia/88_palestina.ts",
  "panama": "na/172_panama.ts",
  "pantai_gading": "afrika/36_pantai_gading.ts",
  "papua_nugini": "oceania/187_papua_nugini.ts",
  "paraguay": "sa/203_paraguay.ts",
  "peru": "sa/204_peru.ts",
  "polandia": "eropa/135_polandia.ts",
  "portugal": "eropa/136_portugal.ts",
  "prancis": "eropa/137_prancis.ts",
  "puerto_rico": "na/173_puerto_rico.ts",
  "qatar": "asia/89_qatar.ts",
  "republik_afrika_tengah": "afrika/37_republik_afrika_tengah.ts",
  "republik_demokratik_kongo": "afrika/38_republik_demokratik_kongo.ts",
  "republik_dominika": "na/174_republik_dominika.ts",
  "republik_rumania": "eropa/138_republik_rumania.ts",
  "republik_serbia": "eropa/139_republik_serbia.ts",
  "republik_sudan": "afrika/39_republik_sudan.ts",
  "republik_tanzania": "afrika/40_republik_tanzania.ts",
  "republik_timor_leste": "asia/90_republik_timor_leste.ts",
  "republik_uganda": "afrika/41_republik_uganda.ts",
  "republik_zambia": "afrika/42_republik_zambia.ts",
  "republik_zimbabwe": "afrika/43_republik_zimbabwe.ts",
  "rusia": "eropa/140_rusia.ts",
  "rwanda": "afrika/44_rwanda.ts",
  "saint_kitts_dan_nevis": "na/175_saint_kitts_dan_nevis.ts",
  "saint_lucia": "na/176_saint_lucia.ts",
  "saint_vincent_dan_grenadine": "na/177_saint_vincent_dan_grenadine.ts",
  "samoa": "oceania/188_samoa.ts",
  "samoa_amerika": "oceania/189_samoa_amerika.ts",
  "san_marino": "eropa/141_san_marino.ts",
  "sao_tome_dan_principe": "afrika/45_sao_tome_dan_principe.ts",
  "selandia_baru": "oceania/190_selandia_baru.ts",
  "senegal": "afrika/46_senegal.ts",
  "seychelles": "afrika/47_seychelles.ts",
  "sierra_leone": "afrika/48_sierra_leone.ts",
  "singapura": "asia/91_singapura.ts",
  "siprus": "eropa/142_siprus.ts",
  "slovenia": "eropa/143_slovenia.ts",
  "slowakia": "eropa/144_slowakia.ts",
  "somalia": "afrika/49_somalia.ts",
  "spanyol": "eropa/145_spanyol.ts",
  "sri_lanka": "asia/92_sri_lanka.ts",
  "sudan_selatan": "afrika/50_sudan_selatan.ts",
  "suriah": "asia/93_suriah.ts",
  "suriname": "sa/205_suriname.ts",
  "swedia": "eropa/146_swedia.ts",
  "swiss": "eropa/147_swiss.ts",
  "tahiti": "oceania/191_tahiti.ts",
  "taiwan": "asia/94_taiwan.ts",
  "tajikistan": "asia/95_tajikistan.ts",
  "tanjung_verde": "afrika/51_tanjung_verde.ts",
  "thailand": "asia/96_thailand.ts",
  "togo": "afrika/52_togo.ts",
  "tonga": "oceania/192_tonga.ts",
  "trinidad_dan_tobago": "na/178_trinidad_dan_tobago.ts",
  "tunisia": "afrika/53_tunisia.ts",
  "turki": "eropa/148_turki.ts",
  "turkmenistan": "asia/97_turkmenistan.ts",
  "tuvalu": "oceania/193_tuvalu.ts",
  "ukraina": "eropa/149_ukraina.ts",
  "uni_emirat_arab": "asia/98_uni_emirat_arab.ts",
  "uruguay": "sa/206_uruguay.ts",
  "uzbekistan": "asia/99_uzbekistan.ts",
  "vanuatu": "oceania/194_vanuatu.ts",
  "vatikan": "eropa/150_vatikan.ts",
  "venezuela": "sa/207_venezuela.ts",
  "vietnam": "asia/100_vietnam.ts",
  "yaman": "asia/101_yaman.ts",
  "yordania": "asia/102_yordania.ts",
  "yunani": "eropa/151_yunani.ts"
};

let createdCount = 0;

tableData.forEach((row) => {
  const norm = normalizeName(row.name);
  const relPath = manualMappings[norm] || countryMap[norm];

  if (!relPath) {
    console.error(`[ERROR] Relative path not found for country: ${row.name} (norm: ${norm})`);
    return;
  }

  const destFile = path.join(databaseSdaDir, relPath);
  const destDir = path.dirname(destFile);

  if (!fs.existsSync(destDir)) {
    fs.mkdirSync(destDir, { recursive: true });
  }

  const varName = path.basename(relPath).replace(/^\d+_/, '').replace(/\.ts$/, '') + '_sda';

  const tsContent = `// @ts-nocheck
const ${varName} = {
  emas: ${row.emas},
  uranium: ${row.uranium},
  batu_bara: ${row.batu_bara},
  minyak_bumi: ${row.minyak_bumi},
  gas_alam: ${row.gas_alam},
  garam: ${row.garam},
  litium: ${row.litium},
  logam_tanah_jarang: ${row.logam_tanah_jarang},
  bijih_besi: ${row.bijih_besi}
};
`;

  fs.writeFileSync(destFile, tsContent, 'utf8');
  createdCount++;
});

console.log(`Successfully generated ${createdCount} SDA TS files in ${databaseSdaDir}.`);
