// country_static_data.ts

export interface CountryStaticData {
  id: number;                       // 🔥 ID negara
  livingCostIndex: number;
  baseLifeExpectancy?: number;      // Opsional, untuk pengembangan selanjutnya
  baseSecurityLevel?: number;       // Opsional
}

export const COUNTRY_STATIC_DATA: Record<string, CountryStaticData> = {
  'afganistan': { id: 1, livingCostIndex: 30 },
  'afrika selatan': { id: 2, livingCostIndex: 42 },
  'albania': { id: 3, livingCostIndex: 52 },
  'aljazair': { id: 4, livingCostIndex: 40 },
  'amerika serikat': { id: 5, livingCostIndex: 86 },
  'andorra': { id: 6, livingCostIndex: 70 },
  'angola': { id: 7, livingCostIndex: 35 },
  'antigua dan barbuda': { id: 8, livingCostIndex: 68 },
  'arab saudi': { id: 9, livingCostIndex: 62 },
  'argentina': { id: 10, livingCostIndex: 48 },
  'armenia': { id: 11, livingCostIndex: 45 },
  'australia': { id: 12, livingCostIndex: 82 },
  'austria': { id: 13, livingCostIndex: 76 },
  'azerbaijan': { id: 14, livingCostIndex: 38 },
  'bahama': { id: 15, livingCostIndex: 72 },
  'bahrain': { id: 16, livingCostIndex: 55 },
  'bangladesh': { id: 17, livingCostIndex: 28 },
  'barbados': { id: 18, livingCostIndex: 65 },
  'belanda': { id: 19, livingCostIndex: 80 },
  'belarus': { id: 20, livingCostIndex: 40 },
  'belgia': { id: 21, livingCostIndex: 77 },
  'belize': { id: 22, livingCostIndex: 45 },
  'benin': { id: 23, livingCostIndex: 32 },
  'bermuda': { id: 24, livingCostIndex: 95 },
  'bhutan': { id: 25, livingCostIndex: 38 },
  'bolivia': { id: 26, livingCostIndex: 35 },
  'bosnia dan hercegovina': { id: 27, livingCostIndex: 45 },
  'botswana': { id: 28, livingCostIndex: 40 },
  'brazil': { id: 29, livingCostIndex: 46 },
  'brunei': { id: 30, livingCostIndex: 58 },
  'bulgaria': { id: 31, livingCostIndex: 48 },
  'burkina faso': { id: 32, livingCostIndex: 30 },
  'burundi': { id: 33, livingCostIndex: 25 },
  'ceko': { id: 34, livingCostIndex: 62 },
  'chad': { id: 35, livingCostIndex: 28 },
  'chile': { id: 36, livingCostIndex: 55 },
  'china': { id: 37, livingCostIndex: 58 },
  'costa rica': { id: 38, livingCostIndex: 52 },
  'curacao': { id: 39, livingCostIndex: 68 },
  'denmark': { id: 40, livingCostIndex: 84 },
  'djibouti': { id: 41, livingCostIndex: 45 },
  'dominika': { id: 42, livingCostIndex: 50 },
  'ekuador': { id: 43, livingCostIndex: 42 },
  'el salvador': { id: 44, livingCostIndex: 40 },
  'eritrea': { id: 45, livingCostIndex: 30 },
  'estonia': { id: 46, livingCostIndex: 60 },
  'eswatini': { id: 47, livingCostIndex: 32 },
  'ethiopia': { id: 48, livingCostIndex: 28 },
  'fiji': { id: 49, livingCostIndex: 48 },
  'filipina': { id: 50, livingCostIndex: 38 },
  'finlandia': { id: 51, livingCostIndex: 80 },
  'gabon': { id: 52, livingCostIndex: 45 },
  'gambia': { id: 53, livingCostIndex: 30 },
  'georgia': { id: 54, livingCostIndex: 42 },
  'ghana': { id: 55, livingCostIndex: 35 },
  'gibraltar': { id: 56, livingCostIndex: 78 },
  'greenland': { id: 57, livingCostIndex: 82 },
  'grenada': { id: 58, livingCostIndex: 55 },
  'guam': { id: 59, livingCostIndex: 72 },
  'guatemala': { id: 60, livingCostIndex: 40 },
  'guiana prancis': { id: 61, livingCostIndex: 50 },
  'guinea': { id: 62, livingCostIndex: 32 },
  'guinea bissau': { id: 63, livingCostIndex: 28 },
  'guyana': { id: 64, livingCostIndex: 38 },
  'haiti': { id: 65, livingCostIndex: 25 },
  'honduras': { id: 66, livingCostIndex: 36 },
  'hong kong': { id: 67, livingCostIndex: 85 },
  'hungaria': { id: 68, livingCostIndex: 55 },
  'india': { id: 69, livingCostIndex: 30 },
  'indonesia': { id: 70, livingCostIndex: 45 },
  'inggris': { id: 71, livingCostIndex: 82 },
  'irak': { id: 72, livingCostIndex: 40 },
  'iran': { id: 73, livingCostIndex: 38 },
  'irlandia': { id: 74, livingCostIndex: 78 },
  'islandia': { id: 75, livingCostIndex: 86 },
  'israel': { id: 76, livingCostIndex: 75 },
  'italia': { id: 77, livingCostIndex: 73 },
  'jamaika': { id: 78, livingCostIndex: 48 },
  'jepang': { id: 79, livingCostIndex: 88 },
  'jerman': { id: 80, livingCostIndex: 79 },
  'kamboja': { id: 81, livingCostIndex: 32 },
  'kamerun': { id: 82, livingCostIndex: 35 },
  'kanada': { id: 83, livingCostIndex: 80 },
  'kazakhstan': { id: 84, livingCostIndex: 42 },
  'kenya': { id: 85, livingCostIndex: 35 },
  'kepulauan faroe': { id: 86, livingCostIndex: 75 },
  'kirgizstan': { id: 87, livingCostIndex: 35 },
  'kiribati': { id: 88, livingCostIndex: 40 },
  'kolombia': { id: 89, livingCostIndex: 45 },
  'komoro': { id: 90, livingCostIndex: 35 },
  'kongo': { id: 91, livingCostIndex: 35 },
  'korea selatan': { id: 92, livingCostIndex: 82 },
  'korea utara': { id: 93, livingCostIndex: 20 },
  'kosovo': { id: 94, livingCostIndex: 42 },
  'kroasia': { id: 95, livingCostIndex: 58 },
  'kuba': { id: 96, livingCostIndex: 30 },
  'kuwait': { id: 97, livingCostIndex: 58 },
  'laos': { id: 98, livingCostIndex: 30 },
  'latvia': { id: 99, livingCostIndex: 55 },
  'lebanon': { id: 100, livingCostIndex: 50 },
  'lesotho': { id: 101, livingCostIndex: 32 },
  'liberia': { id: 102, livingCostIndex: 28 },
  'libya': { id: 103, livingCostIndex: 35 },
  'liechtenstein': { id: 104, livingCostIndex: 92 },
  'lithuania': { id: 105, livingCostIndex: 52 },
  'luksemburg': { id: 106, livingCostIndex: 88 },
  'madagaskar': { id: 107, livingCostIndex: 30 },
  'makau': { id: 108, livingCostIndex: 72 },
  'makedonia utara': { id: 109, livingCostIndex: 48 },
  'malawi': { id: 110, livingCostIndex: 28 },
  'malaysia': { id: 111, livingCostIndex: 48 },
  'maldives': { id: 112, livingCostIndex: 65 },
  'mali': { id: 113, livingCostIndex: 30 },
  'malta': { id: 114, livingCostIndex: 65 },
  'maroko': { id: 115, livingCostIndex: 38 },
  'marshall': { id: 116, livingCostIndex: 45 },
  'mauritania': { id: 117, livingCostIndex: 35 },
  'mauritius': { id: 118, livingCostIndex: 48 },
  'meksiko': { id: 119, livingCostIndex: 48 },
  'mesir': { id: 120, livingCostIndex: 35 },
  'mikronesia': { id: 121, livingCostIndex: 40 },
  'moldova': { id: 122, livingCostIndex: 35 },
  'monako': { id: 123, livingCostIndex: 95 },
  'mongolia': { id: 124, livingCostIndex: 38 },
  'montenegro': { id: 125, livingCostIndex: 50 },
  'mozambik': { id: 126, livingCostIndex: 28 },
  'myanmar': { id: 127, livingCostIndex: 30 },
  'namibia': { id: 128, livingCostIndex: 42 },
  'nauru': { id: 129, livingCostIndex: 45 },
  'nepal': { id: 130, livingCostIndex: 30 },
  'niger': { id: 131, livingCostIndex: 25 },
  'nigeria': { id: 132, livingCostIndex: 32 },
  'nikaragua': { id: 133, livingCostIndex: 38 },
  'norwegia': { id: 134, livingCostIndex: 90 },
  'oman': { id: 135, livingCostIndex: 55 },
  'pakistan': { id: 136, livingCostIndex: 30 },
  'palau': { id: 137, livingCostIndex: 60 },
  'palestina': { id: 138, livingCostIndex: 40 },
  'panama': { id: 139, livingCostIndex: 48 },
  'pantai gading': { id: 140, livingCostIndex: 35 },
  'papua nugini': { id: 141, livingCostIndex: 40 },
  'paraguay': { id: 142, livingCostIndex: 38 },
  'peru': { id: 143, livingCostIndex: 42 },
  'polandia': { id: 144, livingCostIndex: 55 },
  'portugal': { id: 145, livingCostIndex: 62 },
  'prancis': { id: 146, livingCostIndex: 78 },
  'puerto rico': { id: 147, livingCostIndex: 62 },
  'qatar': { id: 148, livingCostIndex: 60 },
  'republik afrika tengah': { id: 149, livingCostIndex: 28 },
  'republik demokratik kongo': { id: 150, livingCostIndex: 25 },
  'republik dominika': { id: 151, livingCostIndex: 45 },
  'republik rumania': { id: 152, livingCostIndex: 50 },
  'republik serbia': { id: 153, livingCostIndex: 48 },
  'republik sudan': { id: 154, livingCostIndex: 32 },
  'republik tanzania': { id: 155, livingCostIndex: 32 },
  'republik timor leste': { id: 156, livingCostIndex: 35 },
  'republik uganda': { id: 157, livingCostIndex: 30 },
  'republik zambia': { id: 158, livingCostIndex: 32 },
  'republik zimbabwe': { id: 159, livingCostIndex: 30 },
  'rusia': { id: 160, livingCostIndex: 48 },
  'rwanda': { id: 161, livingCostIndex: 30 },
  'saint kitts dan nevis': { id: 162, livingCostIndex: 65 },
  'saint lucia': { id: 163, livingCostIndex: 65 },
  'saint vincent dan grenadine': { id: 164, livingCostIndex: 60 },
  'samoa': { id: 165, livingCostIndex: 42 },
  'samoa amerika': { id: 166, livingCostIndex: 50 },
  'san marino': { id: 167, livingCostIndex: 70 },
  'sao tome dan principe': { id: 168, livingCostIndex: 40 },
  'selandia baru': { id: 169, livingCostIndex: 80 },
  'senegal': { id: 170, livingCostIndex: 35 },
  'seychelles': { id: 171, livingCostIndex: 60 },
  'sierra leone': { id: 172, livingCostIndex: 28 },
  'singapura': { id: 173, livingCostIndex: 85 },
  'siprus': { id: 174, livingCostIndex: 62 },
  'slovenia': { id: 175, livingCostIndex: 60 },
  'slowakia': { id: 176, livingCostIndex: 55 },
  'somalia': { id: 177, livingCostIndex: 20 },
  'spanyol': { id: 178, livingCostIndex: 70 },
  'sri lanka': { id: 179, livingCostIndex: 35 },
  'sudan selatan': { id: 180, livingCostIndex: 28 },
  'suriah': { id: 181, livingCostIndex: 25 },
  'suriname': { id: 182, livingCostIndex: 40 },
  'swedia': { id: 183, livingCostIndex: 82 },
  'swiss': { id: 184, livingCostIndex: 92 },
  'tahiti': { id: 185, livingCostIndex: 85 },
  'taiwan': { id: 186, livingCostIndex: 65 },
  'tajikistan': { id: 187, livingCostIndex: 35 },
  'tanjung verde': { id: 188, livingCostIndex: 42 },
  'thailand': { id: 189, livingCostIndex: 42 },
  'togo': { id: 190, livingCostIndex: 32 },
  'tonga': { id: 191, livingCostIndex: 40 },
  'trinidad dan tobago': { id: 192, livingCostIndex: 58 },
  'tunisia': { id: 193, livingCostIndex: 38 },
  'turki': { id: 194, livingCostIndex: 45 },
  'turkmenistan': { id: 195, livingCostIndex: 40 },
  'tuvalu': { id: 196, livingCostIndex: 38 },
  'ukraina': { id: 197, livingCostIndex: 38 },
  'uni emirat arab': { id: 198, livingCostIndex: 65 },
  'uruguay': { id: 199, livingCostIndex: 55 },
  'uzbekistan': { id: 200, livingCostIndex: 38 },
  'vanuatu': { id: 201, livingCostIndex: 45 },
  'vatikan': { id: 202, livingCostIndex: 85 },
  'venezuela': { id: 203, livingCostIndex: 25 },
  'vietnam': { id: 204, livingCostIndex: 38 },
  'yaman': { id: 205, livingCostIndex: 25 },
  'yordania': { id: 206, livingCostIndex: 42 },
  'yunani': { id: 207, livingCostIndex: 60 },
};