export const guyana_diplomasi = [
  { "no": 1, "mitra": "Afganistan", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 2, "mitra": "Afrika Selatan", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 3, "mitra": "Aljazair", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 4, "mitra": "Andorra", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 5, "mitra": "Argentina", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 6, "mitra": "Austria", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 7, "mitra": "Azerbaijan", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 8, "mitra": "Bahama", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 9, "mitra": "Barbados", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 10, "mitra": "Belanda", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 11, "mitra": "Belarus", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 12, "mitra": "Belize", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 13, "mitra": "Bermuda", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 14, "mitra": "Bhutan", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 15, "mitra": "Bosnia dan Hercegovina", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 16, "mitra": "Botswana", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 17, "mitra": "Brazil", "type": "Kedutaan Besar", "status": "Aktif" },
  { "no": 18, "mitra": "Brunei", "type": "Kedutaan Besar", "status": "Aktif" }
];
