-- Database Organisasi: Organisasi Buruh Internasional (ILO)
-- Tipe: PBB

INSERT INTO organisasi_internasional (code, name, type) 
VALUES ('ILO', 'Organisasi Buruh Internasional (ILO)', 'PBB')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO organisasi_membership (organisasi_id, country_id, membership_type) VALUES
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'afganistan' OR name_id = 'afganistan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'afrika selatan' OR name_id = 'afrika selatan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'albania' OR name_id = 'albania'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'aljazair' OR name_id = 'aljazair'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'amerika serikat' OR name_id = 'amerika serikat'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'andorra' OR name_id = 'andorra'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'angola' OR name_id = 'angola'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'antigua dan barbuda' OR name_id = 'antigua dan barbuda'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'arab saudi' OR name_id = 'arab saudi'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'argentina' OR name_id = 'argentina'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'armenia' OR name_id = 'armenia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'australia' OR name_id = 'australia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'austria' OR name_id = 'austria'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'azerbaijan' OR name_id = 'azerbaijan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'bahama' OR name_id = 'bahama'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'bahrain' OR name_id = 'bahrain'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'bangladesh' OR name_id = 'bangladesh'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'barbados' OR name_id = 'barbados'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'belanda' OR name_id = 'belanda'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'belarus' OR name_id = 'belarus'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'belgia' OR name_id = 'belgia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'belize' OR name_id = 'belize'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'benin' OR name_id = 'benin'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'bhutan' OR name_id = 'bhutan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'bolivia' OR name_id = 'bolivia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'bosnia dan hercegovina' OR name_id = 'bosnia dan hercegovina'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'botswana' OR name_id = 'botswana'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'brazil' OR name_id = 'brazil'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'brunei' OR name_id = 'brunei'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'bulgaria' OR name_id = 'bulgaria'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'burkina faso' OR name_id = 'burkina faso'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'burundi' OR name_id = 'burundi'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'ceko' OR name_id = 'ceko'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'chad' OR name_id = 'chad'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'chile' OR name_id = 'chile'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'china' OR name_id = 'china'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'costa rica' OR name_id = 'costa rica'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'denmark' OR name_id = 'denmark'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'djibouti' OR name_id = 'djibouti'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'dominika' OR name_id = 'dominika'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'ekuador' OR name_id = 'ekuador'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'el salvador' OR name_id = 'el salvador'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'eritrea' OR name_id = 'eritrea'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'estonia' OR name_id = 'estonia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'eswatini' OR name_id = 'eswatini'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'ethiopia' OR name_id = 'ethiopia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'fiji' OR name_id = 'fiji'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'filipina' OR name_id = 'filipina'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'finlandia' OR name_id = 'finlandia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'gabon' OR name_id = 'gabon'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'gambia' OR name_id = 'gambia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'georgia' OR name_id = 'georgia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'ghana' OR name_id = 'ghana'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'grenada' OR name_id = 'grenada'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'guatemala' OR name_id = 'guatemala'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'guinea' OR name_id = 'guinea'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'guinea-bissau' OR name_id = 'guinea-bissau'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'guyana' OR name_id = 'guyana'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'haiti' OR name_id = 'haiti'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'honduras' OR name_id = 'honduras'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'hungaria' OR name_id = 'hungaria'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'india' OR name_id = 'india'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'indonesia' OR name_id = 'indonesia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'inggris' OR name_id = 'inggris'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'irak' OR name_id = 'irak'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'iran' OR name_id = 'iran'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'irlandia' OR name_id = 'irlandia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'islandia' OR name_id = 'islandia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'israel' OR name_id = 'israel'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'italia' OR name_id = 'italia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'jamaika' OR name_id = 'jamaika'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'jepang' OR name_id = 'jepang'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'jerman' OR name_id = 'jerman'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'kamboja' OR name_id = 'kamboja'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'kamerun' OR name_id = 'kamerun'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'kanada' OR name_id = 'kanada'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'kazakhstan' OR name_id = 'kazakhstan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'kenya' OR name_id = 'kenya'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'kirgizstan' OR name_id = 'kirgizstan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'kiribati' OR name_id = 'kiribati'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'kolombia' OR name_id = 'kolombia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'komoro' OR name_id = 'komoro'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'kongo' OR name_id = 'kongo'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'korea selatan' OR name_id = 'korea selatan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'korea utara' OR name_id = 'korea utara'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'kosovo' OR name_id = 'kosovo'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'kuba' OR name_id = 'kuba'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'kuwait' OR name_id = 'kuwait'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'laos' OR name_id = 'laos'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'latvia' OR name_id = 'latvia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'lebanon' OR name_id = 'lebanon'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'lesotho' OR name_id = 'lesotho'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'liberia' OR name_id = 'liberia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'libya' OR name_id = 'libya'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'liechtenstein' OR name_id = 'liechtenstein'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'lithuania' OR name_id = 'lithuania'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'luksemburg' OR name_id = 'luksemburg'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'madagaskar' OR name_id = 'madagaskar'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'makedonia utara' OR name_id = 'makedonia utara'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'malawi' OR name_id = 'malawi'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'malaysia' OR name_id = 'malaysia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'maldives' OR name_id = 'maldives'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'mali' OR name_id = 'mali'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'malta' OR name_id = 'malta'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'maroko' OR name_id = 'maroko'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'marshall' OR name_id = 'marshall'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'mauritania' OR name_id = 'mauritania'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'mauritius' OR name_id = 'mauritius'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'meksiko' OR name_id = 'meksiko'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'mesir' OR name_id = 'mesir'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'mikronesia' OR name_id = 'mikronesia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'moldova' OR name_id = 'moldova'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'mongolia' OR name_id = 'mongolia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'montenegro' OR name_id = 'montenegro'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'mozambik' OR name_id = 'mozambik'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'myanmar' OR name_id = 'myanmar'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'namibia' OR name_id = 'namibia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'nauru' OR name_id = 'nauru'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'nepal' OR name_id = 'nepal'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'niger' OR name_id = 'niger'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'nigeria' OR name_id = 'nigeria'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'nikaragua' OR name_id = 'nikaragua'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'norwegia' OR name_id = 'norwegia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'oman' OR name_id = 'oman'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'pakistan' OR name_id = 'pakistan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'palau' OR name_id = 'palau'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'panama' OR name_id = 'panama'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'pantai gading' OR name_id = 'pantai gading'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'papua nugini' OR name_id = 'papua nugini'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'paraguay' OR name_id = 'paraguay'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'peru' OR name_id = 'peru'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'polandia' OR name_id = 'polandia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'portugal' OR name_id = 'portugal'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'qatar' OR name_id = 'qatar'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'republik afrika tengah' OR name_id = 'republik afrika tengah'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'republik demokratik kongo' OR name_id = 'republik demokratik kongo'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'republik dominika' OR name_id = 'republik dominika'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'republik rumania' OR name_id = 'republik rumania'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'republik serbia' OR name_id = 'republik serbia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'republik sudan' OR name_id = 'republik sudan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'republik tanzania' OR name_id = 'republik tanzania'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'republik timor-leste' OR name_id = 'republik timor-leste'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'republik uganda' OR name_id = 'republik uganda'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'republik zambia' OR name_id = 'republik zambia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'republik zimbabwe' OR name_id = 'republik zimbabwe'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'rusia' OR name_id = 'rusia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'rwanda' OR name_id = 'rwanda'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'saint kitts dan nevis' OR name_id = 'saint kitts dan nevis'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'saint lucia' OR name_id = 'saint lucia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'saint vincent dan grenadine' OR name_id = 'saint vincent dan grenadine'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'samoa' OR name_id = 'samoa'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'san marino' OR name_id = 'san marino'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'sao tome dan principe' OR name_id = 'sao tome dan principe'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'selandia baru' OR name_id = 'selandia baru'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'senegal' OR name_id = 'senegal'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'seychelles' OR name_id = 'seychelles'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'sierra leone' OR name_id = 'sierra leone'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'singapura' OR name_id = 'singapura'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'siprus' OR name_id = 'siprus'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'slovenia' OR name_id = 'slovenia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'slowakia' OR name_id = 'slowakia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'somalia' OR name_id = 'somalia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'spanyol' OR name_id = 'spanyol'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'sri lanka' OR name_id = 'sri lanka'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'sudan selatan' OR name_id = 'sudan selatan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'suriah' OR name_id = 'suriah'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'suriname' OR name_id = 'suriname'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'swedia' OR name_id = 'swedia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'swiss' OR name_id = 'swiss'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'tajikistan' OR name_id = 'tajikistan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'tanjung verde' OR name_id = 'tanjung verde'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'thailand' OR name_id = 'thailand'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'togo' OR name_id = 'togo'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'tonga' OR name_id = 'tonga'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'trinidad dan tobago' OR name_id = 'trinidad dan tobago'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'tunisia' OR name_id = 'tunisia'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'turki' OR name_id = 'turki'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'turkmenistan' OR name_id = 'turkmenistan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'tuvalu' OR name_id = 'tuvalu'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'ukraina' OR name_id = 'ukraina'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'uni emirat arab' OR name_id = 'uni emirat arab'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'uruguay' OR name_id = 'uruguay'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'uzbekistan' OR name_id = 'uzbekistan'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'vanuatu' OR name_id = 'vanuatu'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'venezuela' OR name_id = 'venezuela'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'vietnam' OR name_id = 'vietnam'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'yaman' OR name_id = 'yaman'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'yordania' OR name_id = 'yordania'), 'Member'),
  ((SELECT id FROM organisasi_internasional WHERE code = 'ILO'), (SELECT id FROM countries WHERE name_en = 'yunani' OR name_id = 'yunani'), 'Member');