// @ts-nocheck
export const italia_relations = [
  { id: 1, name: "afrika selatan", relation: 50 },
  { id: 2, name: "aljazair", relation: 50 },
  { id: 3, name: "angola", relation: 50 },
  { id: 4, name: "benin", relation: 50 },
  { id: 5, name: "botswana", relation: 50 },
  { id: 6, name: "burkina faso", relation: 50 },
  { id: 7, name: "burundi", relation: 50 },
  { id: 8, name: "chad", relation: 50 },
  { id: 9, name: "djibouti", relation: 50 },
  { id: 10, name: "eritrea", relation: 50 },
  { id: 11, name: "eswatini", relation: 50 },
  { id: 12, name: "ethiopia", relation: 50 },
  { id: 13, name: "gabon", relation: 50 },
  { id: 14, name: "gambia", relation: 50 },
  { id: 15, name: "ghana", relation: 50 },
  { id: 16, name: "guinea", relation: 50 },
  { id: 17, name: "guinea bissau", relation: 50 },
  { id: 18, name: "kamerun", relation: 50 },
  { id: 19, name: "kenya", relation: 50 },
  { id: 20, name: "komoro", relation: 50 },
  { id: 21, name: "kongo", relation: 50 },
  { id: 22, name: "lesotho", relation: 50 },
  { id: 23, name: "liberia", relation: 50 },
  { id: 24, name: "libya", relation: 70 },
  { id: 25, name: "madagaskar", relation: 50 },
  { id: 26, name: "malawi", relation: 50 },
  { id: 27, name: "mali", relation: 50 },
  { id: 28, name: "maroko", relation: 50 },
  { id: 29, name: "mauritania", relation: 50 },
  { id: 30, name: "mauritius", relation: 50 },
  { id: 31, name: "mesir", relation: 50 },
  { id: 32, name: "mozambik", relation: 50 },
  { id: 33, name: "namibia", relation: 50 },
  { id: 34, name: "niger", relation: 50 },
  { id: 35, name: "nigeria", relation: 50 },
  { id: 36, name: "pantai gading", relation: 50 },
  { id: 37, name: "republik afrika tengah", relation: 50 },
  { id: 38, name: "republik demokratik kongo", relation: 50 },
  { id: 39, name: "republik sudan", relation: 50 },
  { id: 40, name: "republik tanzania", relation: 50 },
  { id: 41, name: "republik uganda", relation: 50 },
  { id: 42, name: "republik zambia", relation: 50 },
  { id: 43, name: "republik zimbabwe", relation: 50 },
  { id: 44, name: "rwanda", relation: 50 },
  { id: 45, name: "sao tome dan principe", relation: 50 },
  { id: 46, name: "senegal", relation: 50 },
  { id: 47, name: "seychelles", relation: 50 },
  { id: 48, name: "sierra leone", relation: 50 },
  { id: 49, name: "somalia", relation: 50 },
  { id: 50, name: "sudan selatan", relation: 50 },
  { id: 51, name: "tanjung verde", relation: 50 },
  { id: 52, name: "togo", relation: 50 },
  { id: 53, name: "tunisia", relation: 70 },
  { id: 54, name: "afganistan", relation: 50 },
  { id: 55, name: "arab saudi", relation: 50 },
  { id: 56, name: "armenia", relation: 50 },
  { id: 57, name: "azerbaijan", relation: 50 },
  { id: 58, name: "bahrain", relation: 50 },
  { id: 59, name: "bangladesh", relation: 50 },
  { id: 60, name: "bhutan", relation: 50 },
  { id: 61, name: "brunei", relation: 50 },
  { id: 62, name: "china", relation: 50 },
  { id: 63, name: "filipina", relation: 50 },
  { id: 64, name: "georgia", relation: 50 },
  { id: 65, name: "hong kong", relation: 50 },
  { id: 66, name: "india", relation: 50 },
  { id: 67, name: "indonesia", relation: 60 },
  { id: 68, name: "irak", relation: 50 },
  { id: 69, name: "iran", relation: 50 },
  { id: 70, name: "israel", relation: 50 },
  { id: 71, name: "jepang", relation: 50 },
  { id: 72, name: "kamboja", relation: 50 },
  { id: 73, name: "kazakhstan", relation: 50 },
  { id: 74, name: "kirgizstan", relation: 50 },
  { id: 75, name: "korea selatan", relation: 50 },
  { id: 76, name: "korea utara", relation: 50 },
  { id: 77, name: "kuwait", relation: 50 },
  { id: 78, name: "laos", relation: 50 },
  { id: 79, name: "lebanon", relation: 50 },
  { id: 80, name: "makau", relation: 50 },
  { id: 81, name: "malaysia", relation: 50 },
  { id: 82, name: "maldives", relation: 50 },
  { id: 83, name: "mongolia", relation: 50 },
  { id: 84, name: "myanmar", relation: 50 },
  { id: 85, name: "nepal", relation: 50 },
  { id: 86, name: "oman", relation: 50 },
  { id: 87, name: "pakistan", relation: 50 },
  { id: 88, name: "palestina", relation: 50 },
  { id: 89, name: "qatar", relation: 50 },
  { id: 90, name: "republik timor leste", relation: 50 },
  { id: 91, name: "singapura", relation: 50 },
  { id: 92, name: "sri lanka", relation: 50 },
  { id: 93, name: "suriah", relation: 50 },
  { id: 94, name: "taiwan", relation: 50 },
  { id: 95, name: "tajikistan", relation: 50 },
  { id: 96, name: "thailand", relation: 50 },
  { id: 97, name: "turkmenistan", relation: 50 },
  { id: 98, name: "uni emirat arab", relation: 50 },
  { id: 99, name: "uzbekistan", relation: 50 },
  { id: 100, name: "vietnam", relation: 50 },
  { id: 101, name: "yaman", relation: 50 },
  { id: 102, name: "yordania", relation: 50 },
  { id: 103, name: "albania", relation: 85 },
  { id: 104, name: "andorra", relation: 50 },
  { id: 105, name: "austria", relation: 85 },
  { id: 106, name: "belanda", relation: 85 },
  { id: 107, name: "belarus", relation: 50 },
  { id: 108, name: "belgia", relation: 85 },
  { id: 109, name: "bosnia dan hercegovina", relation: 50 },
  { id: 110, name: "bulgaria", relation: 85 },
  { id: 111, name: "ceko", relation: 85 },
  { id: 112, name: "denmark", relation: 85 },
  { id: 113, name: "estonia", relation: 85 },
  { id: 114, name: "finlandia", relation: 85 },
  { id: 115, name: "gibraltar", relation: 50 },
  { id: 116, name: "hungaria", relation: 85 },
  { id: 117, name: "inggris", relation: 85 },
  { id: 118, name: "irlandia", relation: 85 },
  { id: 119, name: "islandia", relation: 85 },
  { id: 120, name: "italia", relation: 100 },
  { id: 121, name: "jerman", relation: 85 },
  { id: 122, name: "kepulauan faroe", relation: 50 },
  { id: 123, name: "kosovo", relation: 50 },
  { id: 124, name: "kroasia", relation: 85 },
  { id: 125, name: "latvia", relation: 85 },
  { id: 126, name: "liechtenstein", relation: 50 },
  { id: 127, name: "lithuania", relation: 85 },
  { id: 128, name: "luksemburg", relation: 50 },
  { id: 129, name: "makedonia utara", relation: 85 },
  { id: 130, name: "malta", relation: 50 },
  { id: 131, name: "moldova", relation: 50 },
  { id: 132, name: "monako", relation: 50 },
  { id: 133, name: "montenegro", relation: 85 },
  { id: 134, name: "norwegia", relation: 85 },
  { id: 135, name: "polandia", relation: 85 },
  { id: 136, name: "portugal", relation: 85 },
  { id: 137, name: "prancis", relation: 85 },
  { id: 138, name: "republik rumania", relation: 85 },
  { id: 139, name: "republik serbia", relation: 50 },
  { id: 140, name: "rusia", relation: 50 },
  { id: 141, name: "san marino", relation: 50 },
  { id: 142, name: "siprus", relation: 50 },
  { id: 143, name: "slovenia", relation: 85 },
  { id: 144, name: "slowakia", relation: 85 },
  { id: 145, name: "spanyol", relation: 85 },
  { id: 146, name: "swedia", relation: 85 },
  { id: 147, name: "swiss", relation: 85 },
  { id: 148, name: "turki", relation: 85 },
  { id: 149, name: "ukraina", relation: 50 },
  { id: 150, name: "vatikan", relation: 50 },
  { id: 151, name: "yunani", relation: 85 },
  { id: 152, name: "amerika serikat", relation: 90 },
  { id: 153, name: "antigua dan barbuda", relation: 50 },
  { id: 154, name: "bahama", relation: 50 },
  { id: 155, name: "barbados", relation: 50 },
  { id: 156, name: "belize", relation: 50 },
  { id: 157, name: "bermuda", relation: 50 },
  { id: 158, name: "costa rica", relation: 50 },
  { id: 159, name: "curacao", relation: 50 },
  { id: 160, name: "dominika", relation: 50 },
  { id: 161, name: "el salvador", relation: 50 },
  { id: 162, name: "greenland", relation: 50 },
  { id: 163, name: "grenada", relation: 50 },
  { id: 164, name: "guatemala", relation: 50 },
  { id: 165, name: "haiti", relation: 50 },
  { id: 166, name: "honduras", relation: 50 },
  { id: 167, name: "jamaika", relation: 50 },
  { id: 168, name: "kanada", relation: 85 },
  { id: 169, name: "kuba", relation: 50 },
  { id: 170, name: "meksiko", relation: 50 },
  { id: 171, name: "nikaragua", relation: 50 },
  { id: 172, name: "panama", relation: 50 },
  { id: 173, name: "puerto rico", relation: 50 },
  { id: 174, name: "republik dominika", relation: 50 },
  { id: 175, name: "saint kitts dan nevis", relation: 50 },
  { id: 176, name: "saint lucia", relation: 50 },
  { id: 177, name: "saint vincent dan grenadine", relation: 50 },
  { id: 178, name: "trinidad dan tobago", relation: 50 },
  { id: 179, name: "australia", relation: 50 },
  { id: 180, name: "fiji", relation: 50 },
  { id: 181, name: "guam", relation: 50 },
  { id: 182, name: "kiribati", relation: 50 },
  { id: 183, name: "marshall", relation: 50 },
  { id: 184, name: "mikronesia", relation: 50 },
  { id: 185, name: "nauru", relation: 50 },
  { id: 186, name: "palau", relation: 50 },
  { id: 187, name: "papua nugini", relation: 50 },
  { id: 188, name: "samoa", relation: 50 },
  { id: 189, name: "samoa amerika", relation: 50 },
  { id: 190, name: "selandia baru", relation: 50 },
  { id: 191, name: "tahiti", relation: 50 },
  { id: 192, name: "tonga", relation: 50 },
  { id: 193, name: "tuvalu", relation: 50 },
  { id: 194, name: "vanuatu", relation: 50 },
  { id: 195, name: "argentina", relation: 50 },
  { id: 196, name: "bolivia", relation: 50 },
  { id: 197, name: "brazil", relation: 50 },
  { id: 198, name: "chile", relation: 50 },
  { id: 199, name: "ekuador", relation: 50 },
  { id: 200, name: "guiana prancis", relation: 85 },
  { id: 201, name: "guyana", relation: 50 },
  { id: 202, name: "kolombia", relation: 50 },
  { id: 203, name: "paraguay", relation: 50 },
  { id: 204, name: "peru", relation: 50 },
  { id: 205, name: "suriname", relation: 50 },
  { id: 206, name: "uruguay", relation: 50 },
  { id: 207, name: "venezuela", relation: 50 }
];
