// @ts-nocheck
// Auto-generated Relations Index
const allRelations: { [key: string]: { id: number; name: string; relation: number }[] } = {
  "afrika selatan": afrika_selatan_relations,
  "aljazair": aljazair_relations,
  "angola": angola_relations,
  "benin": benin_relations,
  "botswana": botswana_relations,
  "burkina faso": burkina_faso_relations,
  "burundi": burundi_relations,
  "chad": chad_relations,
  "djibouti": djibouti_relations,
  "eritrea": eritrea_relations,
  "eswatini": eswatini_relations,
  "ethiopia": ethiopia_relations,
  "gabon": gabon_relations,
  "gambia": gambia_relations,
  "ghana": ghana_relations,
  "guinea": guinea_relations,
  "guinea bissau": guinea_bissau_relations,
  "kamerun": kamerun_relations,
  "kenya": kenya_relations,
  "komoro": komoro_relations,
  "kongo": kongo_relations,
  "lesotho": lesotho_relations,
  "liberia": liberia_relations,
  "libya": libya_relations,
  "madagaskar": madagaskar_relations,
  "malawi": malawi_relations,
  "mali": mali_relations,
  "maroko": maroko_relations,
  "mauritania": mauritania_relations,
  "mauritius": mauritius_relations,
  "mesir": mesir_relations,
  "mozambik": mozambik_relations,
  "namibia": namibia_relations,
  "niger": niger_relations,
  "nigeria": nigeria_relations,
  "pantai gading": pantai_gading_relations,
  "republik afrika tengah": republik_afrika_tengah_relations,
  "republik demokratik kongo": republik_demokratik_kongo_relations,
  "republik sudan": republik_sudan_relations,
  "republik tanzania": republik_tanzania_relations,
  "republik uganda": republik_uganda_relations,
  "republik zambia": republik_zambia_relations,
  "republik zimbabwe": republik_zimbabwe_relations,
  "rwanda": rwanda_relations,
  "sao tome dan principe": sao_tome_dan_principe_relations,
  "senegal": senegal_relations,
  "seychelles": seychelles_relations,
  "sierra leone": sierra_leone_relations,
  "somalia": somalia_relations,
  "sudan selatan": sudan_selatan_relations,
  "tanjung verde": tanjung_verde_relations,
  "togo": togo_relations,
  "tunisia": tunisia_relations,
  "afganistan": afganistan_relations,
  "arab saudi": arab_saudi_relations,
  "armenia": armenia_relations,
  "azerbaijan": azerbaijan_relations,
  "bahrain": bahrain_relations,
  "bangladesh": bangladesh_relations,
  "bhutan": bhutan_relations,
  "brunei": brunei_relations,
  "china": china_relations,
  "filipina": filipina_relations,
  "georgia": georgia_relations,
  "hong kong": hong_kong_relations,
  "india": india_relations,
  "indonesia": indonesia_relations,
  "irak": irak_relations,
  "iran": iran_relations,
  "israel": israel_relations,
  "jepang": jepang_relations,
  "kamboja": kamboja_relations,
  "kazakhstan": kazakhstan_relations,
  "kirgizstan": kirgizstan_relations,
  "korea selatan": korea_selatan_relations,
  "korea utara": korea_utara_relations,
  "kuwait": kuwait_relations,
  "laos": laos_relations,
  "lebanon": lebanon_relations,
  "makau": makau_relations,
  "malaysia": malaysia_relations,
  "maldives": maldives_relations,
  "mongolia": mongolia_relations,
  "myanmar": myanmar_relations,
  "nepal": nepal_relations,
  "oman": oman_relations,
  "pakistan": pakistan_relations,
  "palestina": palestina_relations,
  "qatar": qatar_relations,
  "republik timor leste": republik_timor_leste_relations,
  "singapura": singapura_relations,
  "sri lanka": sri_lanka_relations,
  "suriah": suriah_relations,
  "taiwan": taiwan_relations,
  "tajikistan": tajikistan_relations,
  "thailand": thailand_relations,
  "turkmenistan": turkmenistan_relations,
  "uni emirat arab": uni_emirat_arab_relations,
  "uzbekistan": uzbekistan_relations,
  "vietnam": vietnam_relations,
  "yaman": yaman_relations,
  "yordania": yordania_relations,
  "albania": albania_relations,
  "andorra": andorra_relations,
  "austria": austria_relations,
  "belanda": belanda_relations,
  "belarus": belarus_relations,
  "belgia": belgia_relations,
  "bosnia dan hercegovina": bosnia_dan_hercegovina_relations,
  "bulgaria": bulgaria_relations,
  "ceko": ceko_relations,
  "denmark": denmark_relations,
  "estonia": estonia_relations,
  "finlandia": finlandia_relations,
  "gibraltar": gibraltar_relations,
  "hungaria": hungaria_relations,
  "inggris": inggris_relations,
  "irlandia": irlandia_relations,
  "islandia": islandia_relations,
  "italia": italia_relations,
  "jerman": jerman_relations,
  "kepulauan faroe": kepulauan_faroe_relations,
  "kosovo": kosovo_relations,
  "kroasia": kroasia_relations,
  "latvia": latvia_relations,
  "liechtenstein": liechtenstein_relations,
  "lithuania": lithuania_relations,
  "luksemburg": luksemburg_relations,
  "makedonia utara": makedonia_utara_relations,
  "malta": malta_relations,
  "moldova": moldova_relations,
  "monako": monako_relations,
  "montenegro": montenegro_relations,
  "norwegia": norwegia_relations,
  "polandia": polandia_relations,
  "portugal": portugal_relations,
  "prancis": prancis_relations,
  "republik rumania": republik_rumania_relations,
  "republik serbia": republik_serbia_relations,
  "rusia": rusia_relations,
  "san marino": san_marino_relations,
  "siprus": siprus_relations,
  "slovenia": slovenia_relations,
  "slowakia": slowakia_relations,
  "spanyol": spanyol_relations,
  "swedia": swedia_relations,
  "swiss": swiss_relations,
  "turki": turki_relations,
  "ukraina": ukraina_relations,
  "vatikan": vatikan_relations,
  "yunani": yunani_relations,
  "amerika serikat": amerika_serikat_relations,
  "antigua dan barbuda": antigua_dan_barbuda_relations,
  "bahama": bahama_relations,
  "barbados": barbados_relations,
  "belize": belize_relations,
  "bermuda": bermuda_relations,
  "costa rica": costa_rica_relations,
  "curacao": curacao_relations,
  "dominika": dominika_relations,
  "el salvador": el_salvador_relations,
  "greenland": greenland_relations,
  "grenada": grenada_relations,
  "guatemala": guatemala_relations,
  "haiti": haiti_relations,
  "honduras": honduras_relations,
  "jamaika": jamaika_relations,
  "kanada": kanada_relations,
  "kuba": kuba_relations,
  "meksiko": meksiko_relations,
  "nikaragua": nikaragua_relations,
  "panama": panama_relations,
  "puerto rico": puerto_rico_relations,
  "republik dominika": republik_dominika_relations,
  "saint kitts dan nevis": saint_kitts_dan_nevis_relations,
  "saint lucia": saint_lucia_relations,
  "saint vincent dan grenadine": saint_vincent_dan_grenadine_relations,
  "trinidad dan tobago": trinidad_dan_tobago_relations,
  "australia": australia_relations,
  "fiji": fiji_relations,
  "guam": guam_relations,
  "kiribati": kiribati_relations,
  "marshall": marshall_relations,
  "mikronesia": mikronesia_relations,
  "nauru": nauru_relations,
  "palau": palau_relations,
  "papua nugini": papua_nugini_relations,
  "samoa": samoa_relations,
  "samoa amerika": samoa_amerika_relations,
  "selandia baru": selandia_baru_relations,
  "tahiti": tahiti_relations,
  "tonga": tonga_relations,
  "tuvalu": tuvalu_relations,
  "vanuatu": vanuatu_relations,
  "argentina": argentina_relations,
  "bolivia": bolivia_relations,
  "brazil": brazil_relations,
  "chile": chile_relations,
  "ekuador": ekuador_relations,
  "guiana prancis": guiana_prancis_relations,
  "guyana": guyana_relations,
  "kolombia": kolombia_relations,
  "paraguay": paraguay_relations,
  "peru": peru_relations,
  "suriname": suriname_relations,
  "uruguay": uruguay_relations,
  "venezuela": venezuela_relations,
};




