-- Hubungan Bilateral untuk indonesia
INSERT INTO hubungan_negara (country_id, target_country_id, relation_value) VALUES
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'afganistan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'afrika selatan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'albania'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'aljazair'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'amerika serikat'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'andorra'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'angola'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'antigua dan barbuda'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'arab saudi'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'argentina'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'armenia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'australia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'austria'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'azerbaijan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'bahama'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'bahrain'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'bangladesh'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'barbados'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'belanda'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'belarus'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'belgia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'belize'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'benin'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'bermuda'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'bhutan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'bolivia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'bosnia dan hercegovina'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'botswana'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'brazil'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'brunei'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'bulgaria'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'burkina faso'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'burundi'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'ceko'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'chad'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'chile'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'china'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'costa rica'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'curacao'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'denmark'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'djibouti'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'dominika'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'ekuador'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'el salvador'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'eritrea'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'estonia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'eswatini'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'ethiopia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'fiji'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'filipina'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'finlandia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'gabon'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'gambia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'georgia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'ghana'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'gibraltar'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'greenland'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'grenada'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'guam'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'guatemala'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'guiana prancis'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'guinea'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'guinea bissau'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'guyana'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'haiti'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'honduras'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'hong kong'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'hungaria'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'india'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'inggris'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'irak'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'iran'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'irlandia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'islandia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'israel'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'italia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'jamaika'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'jepang'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'jerman'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kamboja'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kamerun'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kanada'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kazakhstan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kenya'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kepulauan faroe'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kirgizstan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kiribati'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kolombia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'komoro'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kongo'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'korea selatan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'korea utara'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kosovo'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kroasia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kuba'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'kuwait'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'laos'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'latvia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'lebanon'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'lesotho'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'liberia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'libya'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'liechtenstein'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'lithuania'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'luksemburg'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'madagaskar'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'makau'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'makedonia utara'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'malawi'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'malaysia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'maldives'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'mali'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'malta'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'maroko'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'marshall'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'mauritania'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'mauritius'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'meksiko'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'mesir'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'mikronesia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'moldova'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'monako'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'mongolia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'montenegro'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'mozambik'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'myanmar'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'namibia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'nauru'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'nepal'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'niger'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'nigeria'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'nikaragua'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'norwegia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'oman'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'pakistan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'palau'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'palestina'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'panama'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'pantai gading'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'papua nugini'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'paraguay'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'peru'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'polandia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'portugal'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'prancis'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'puerto rico'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'qatar'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'republik afrika tengah'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'republik demokratik kongo'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'republik dominika'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'republik rumania'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'republik serbia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'republik sudan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'republik tanzania'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'republik timor leste'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'republik uganda'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'republik zambia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'republik zimbabwe'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'rusia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'rwanda'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'saint kitts dan nevis'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'saint lucia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'saint vincent dan grenadine'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'samoa'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'samoa amerika'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'san marino'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'sao tome dan principe'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'selandia baru'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'senegal'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'seychelles'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'sierra leone'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'singapura'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'siprus'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'slovenia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'slowakia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'somalia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'spanyol'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'sri lanka'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'sudan selatan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'suriah'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'suriname'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'swedia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'swiss'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'tahiti'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'taiwan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'tajikistan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'tanjung verde'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'thailand'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'togo'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'tonga'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'trinidad dan tobago'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'tunisia'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'turki'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'turkmenistan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'tuvalu'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'ukraina'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'uni emirat arab'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'uruguay'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'uzbekistan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'vanuatu'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'vatikan'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'venezuela'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'vietnam'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'yaman'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'yordania'), 50),
  ((SELECT id FROM countries WHERE name_en = 'indonesia'), (SELECT id FROM countries WHERE name_en = 'yunani'), 50);