// @ts-nocheck
export interface VehicleData {
  sepeda_motor: number;
  mobil: number;
  bus: number;
  truk: number;
}

const vehicleDatabase: Record<string, VehicleData> = {
  "eritrea".eritreaVehicles,
  "eswatini".eswatiniVehicles,
  "ethiopia".ethiopiaVehicles,
  "gabon".gabonVehicles,
  "gambia".gambiaVehicles,
  "ghana".ghanaVehicles,
  "guinea".guineaVehicles,
  "guinea_bissau".guineaBissauVehicles,
  "kamerun".kamerunVehicles,
  "kenya".kenyaVehicles,
  "afrika_selatan".afrikaSelatanVehicles,
  "komoro".komoroVehicles,
  "kongo".kongoVehicles,
  "lesotho".lesothoVehicles,
  "liberia".liberiaVehicles,
  "libya".libyaVehicles,
  "madagaskar".madagaskarVehicles,
  "malawi".malawiVehicles,
  "mali".maliVehicles,
  "maroko".marokoVehicles,
  "mauritania".mauritaniaVehicles,
  "aljazair".aljazairVehicles,
  "mauritius".mauritiusVehicles,
  "mesir".mesirVehicles,
  "mozambik".mozambikVehicles,
  "namibia".namibiaVehicles,
  "niger".nigerVehicles,
  "nigeria".nigeriaVehicles,
  "pantai_gading".pantaiGadingVehicles,
  "republik_afrika_tengah".republikAfrikaTengahVehicles,
  "republik_demokratik_kongo".republikDemokratikKongoVehicles,
  "republik_sudan".republikSudanVehicles,
  "angola".angolaVehicles,
  "republik_tanzania".republikTanzaniaVehicles,
  "republik_uganda".republikUgandaVehicles,
  "republik_zambia".republikZambiaVehicles,
  "republik_zimbabwe".republikZimbabweVehicles,
  "rwanda".rwandaVehicles,
  "sao_tome_dan_principe".saoTomeDanPrincipeVehicles,
  "senegal".senegalVehicles,
  "seychelles".seychellesVehicles,
  "sierra_leone".sierraLeoneVehicles,
  "somalia".somaliaVehicles,
  "benin".beninVehicles,
  "sudan_selatan".sudanSelatanVehicles,
  "tanjung_verde".tanjungVerdeVehicles,
  "togo".togoVehicles,
  "tunisia".tunisiaVehicles,
  "botswana".botswanaVehicles,
  "burkina_faso".burkinaFasoVehicles,
  "burundi".burundiVehicles,
  "chad".chadVehicles,
  "djibouti".djiboutiVehicles,
  "vietnam".vietnamVehicles,
  "yaman".yamanVehicles,
  "yordania".yordaniaVehicles,
  "afganistan".afganistanVehicles,
  "arab_saudi".arabSaudiVehicles,
  "armenia".armeniaVehicles,
  "azerbaijan".azerbaijanVehicles,
  "bahrain".bahrainVehicles,
  "bangladesh".bangladeshVehicles,
  "bhutan".bhutanVehicles,
  "brunei".bruneiVehicles,
  "china".chinaVehicles,
  "filipina".filipinaVehicles,
  "georgia".georgiaVehicles,
  "hong_kong".hongKongVehicles,
  "india".indiaVehicles,
  "indonesia".indonesiaVehicles,
  "irak".irakVehicles,
  "iran".iranVehicles,
  "israel".israelVehicles,
  "jepang".jepangVehicles,
  "kamboja".kambojaVehicles,
  "kazakhstan".kazakhstanVehicles,
  "kirgizstan".kirgizstanVehicles,
  "korea_selatan".koreaSelatanVehicles,
  "korea_utara".koreaUtaraVehicles,
  "kuwait".kuwaitVehicles,
  "laos".laosVehicles,
  "lebanon".lebanonVehicles,
  "makau".makauVehicles,
  "malaysia".malaysiaVehicles,
  "maldives".maldivesVehicles,
  "mongolia".mongoliaVehicles,
  "myanmar".myanmarVehicles,
  "nepal".nepalVehicles,
  "oman".omanVehicles,
  "pakistan".pakistanVehicles,
  "palestina".palestinaVehicles,
  "qatar".qatarVehicles,
  "republik_timor_leste".republikTimorLesteVehicles,
  "singapura".singapuraVehicles,
  "sri_lanka".sriLankaVehicles,
  "suriah".suriahVehicles,
  "taiwan".taiwanVehicles,
  "tajikistan".tajikistanVehicles,
  "thailand".thailandVehicles,
  "turkmenistan".turkmenistanVehicles,
  "uni_emirat_arab".uniEmiratArabVehicles,
  "uzbekistan".uzbekistanVehicles,
  "albania".albaniaVehicles,
  "andorra".andorraVehicles,
  "austria".austriaVehicles,
  "belanda".belandaVehicles,
  "belarus".belarusVehicles,
  "belgia".belgiaVehicles,
  "bosnia_dan_hercegovina".bosniaDanHercegovinaVehicles,
  "bulgaria".bulgariaVehicles,
  "ceko".cekoVehicles,
  "denmark".denmarkVehicles,
  "estonia".estoniaVehicles,
  "finlandia".finlandiaVehicles,
  "gibraltar".gibraltarVehicles,
  "hungaria".hungariaVehicles,
  "inggris".inggrisVehicles,
  "irlandia".irlandiaVehicles,
  "islandia".islandiaVehicles,
  "italia".italiaVehicles,
  "jerman".jermanVehicles,
  "kepulauan_faroe".kepulauanFaroeVehicles,
  "kosovo".kosovoVehicles,
  "kroasia".kroasiaVehicles,
  "latvia".latviaVehicles,
  "liechtenstein".liechtensteinVehicles,
  "lithuania".lithuaniaVehicles,
  "luksemburg".luksemburgVehicles,
  "makedonia_utara".makedoniaUtaraVehicles,
  "malta".maltaVehicles,
  "moldova".moldovaVehicles,
  "monako".monakoVehicles,
  "montenegro".montenegroVehicles,
  "norwegia".norwegiaVehicles,
  "polandia".polandiaVehicles,
  "portugal".portugalVehicles,
  "prancis".prancisVehicles,
  "republik_rumania".republikRumaniaVehicles,
  "republik_serbia".republikSerbiaVehicles,
  "rusia".rusiaVehicles,
  "san_marino".sanMarinoVehicles,
  "siprus".siprusVehicles,
  "slovenia".sloveniaVehicles,
  "slowakia".slowakiaVehicles,
  "spanyol".spanyolVehicles,
  "swedia".swediaVehicles,
  "swiss".swissVehicles,
  "turki".turkiVehicles,
  "ukraina".ukrainaVehicles,
  "vatikan".vatikanVehicles,
  "yunani".yunaniVehicles,
  "amerika_serikat".amerikaSerikatVehicles,
  "antigua_dan_barbuda".antiguaDanBarbudaVehicles,
  "bahama".bahamaVehicles,
  "barbados".barbadosVehicles,
  "belize".belizeVehicles,
  "bermuda".bermudaVehicles,
  "costa_rica".costaRicaVehicles,
  "curacao".curacaoVehicles,
  "dominika".dominikaVehicles,
  "el_salvador".elSalvadorVehicles,
  "greenland".greenlandVehicles,
  "grenada".grenadaVehicles,
  "guatemala".guatemalaVehicles,
  "haiti".haitiVehicles,
  "honduras".hondurasVehicles,
  "jamaika".jamaikaVehicles,
  "kanada".kanadaVehicles,
  "kuba".kubaVehicles,
  "meksiko".meksikoVehicles,
  "nikaragua".nikaraguaVehicles,
  "panama".panamaVehicles,
  "puerto_rico".puertoRicoVehicles,
  "republik_dominika".republikDominikaVehicles,
  "saint_kitts_dan_nevis".saintKittsDanNevisVehicles,
  "saint_lucia".saintLuciaVehicles,
  "saint_vincent_dan_grenadine".saintVincentDanGrenadineVehicles,
  "trinidad_dan_tobago".trinidadDanTobagoVehicles,
  "argentina".argentinaVehicles,
  "bolivia".boliviaVehicles,
  "brazil".brazilVehicles,
  "chile".chileVehicles,
  "ekuador".ekuadorVehicles,
  "guiana_prancis".guianaPrancisVehicles,
  "guyana".guyanaVehicles,
  "kolombia".kolombiaVehicles,
  "paraguay".paraguayVehicles,
  "peru".peruVehicles,
  "suriname".surinameVehicles,
  "uruguay".uruguayVehicles,
  "venezuela".venezuelaVehicles,
  "australia".australiaVehicles,
  "fiji".fijiVehicles,
  "guam".guamVehicles,
  "kiribati".kiribatiVehicles,
  "marshall".marshallVehicles,
  "mikronesia".mikronesiaVehicles,
  "nauru".nauruVehicles,
  "palau".palauVehicles,
  "papua_nugini".papuaNuginiVehicles,
  "samoa".samoaVehicles,
  "samoa_amerika".samoaAmerikaVehicles,
  "selandia_baru".selandiaBaruVehicles,
  "tahiti".tahitiVehicles,
  "tonga".tongaVehicles,
  "tuvalu".tuvaluVehicles,
  "vanuatu".vanuatuVehicles,
};

const getVehicleData = (countryId: string) => {
  return vehicleDatabase[countryId.toLowerCase()] || {
    sepeda_motor: 0,
    mobil: 0,
    bus: 0,
    truk: 0
  };
};

export * from "./afrika";
export * from "./asia";
export * from "./eropa";
export * from "./na";
export * from "./sa";
export * from "./oceania";



