import os, re, glob

root = r'c:\utama\project\project-sendiri\EM\json\semua_fitur_negara\1_pembangunan\1_produksi\2_sektor_mineral_kritis'

# manual mapping from country display name to exact file path
mapping = {
    'Afganistan': os.path.join(root, 'asia', '54_afganistan.ts'),
    'Arab Saudi': os.path.join(root, 'asia', '55_arab_saudi.ts'),
    'Armenia': os.path.join(root, 'asia', '56_armenia.ts'),
    'Azerbaijan': os.path.join(root, 'asia', '57_azerbaijan.ts'),
    'Bahrain': os.path.join(root, 'asia', '58_bahrain.ts'),
    'Bangladesh': os.path.join(root, 'asia', '59_bangladesh.ts'),
    'Bhutan': os.path.join(root, 'asia', '60_bhutan.ts'),
    'Brunei': os.path.join(root, 'asia', '61_brunei.ts'),
    'China': os.path.join(root, 'asia', '62_china.ts'),
    'Filipina': os.path.join(root, 'asia', '63_filipina.ts'),
    'Georgia': os.path.join(root, 'asia', '64_georgia.ts'),
    'Hong kong': os.path.join(root, 'asia', '65_hong_kong.ts'),
    'India': os.path.join(root, 'asia', '66_india.ts'),
    'Indonesia': os.path.join(root, 'asia', '67_indonesia.ts'),
    'Irak': os.path.join(root, 'asia', '68_irak.ts'),
    'Iran': os.path.join(root, 'asia', '69_iran.ts'),
    'Israel': os.path.join(root, 'asia', '70_israel.ts'),
    'Jepang': os.path.join(root, 'asia', '71_jepang.ts'),
    'Kamboja': os.path.join(root, 'asia', '72_kamboja.ts'),
    'Kazakhstan': os.path.join(root, 'asia', '73_kazakhstan.ts'),
    'Kirgizstan': os.path.join(root, 'asia', '74_kirgizstan.ts'),
    'Korea Selatan': os.path.join(root, 'asia', '75_korea_selatan.ts'),
    'Korea Utara': os.path.join(root, 'asia', '76_korea_utara.ts'),
    'Kuwait': os.path.join(root, 'asia', '77_kuwait.ts'),
    'Laos': os.path.join(root, 'asia', '78_laos.ts'),
    'Lebanon': os.path.join(root, 'asia', '79_lebanon.ts'),
    'Makau': os.path.join(root, 'asia', '80_makau.ts'),
    'Malaysia': os.path.join(root, 'asia', '81_malaysia.ts'),
    'Maldives': os.path.join(root, 'asia', '82_maldives.ts'),
    'Mongolia': os.path.join(root, 'asia', '83_mongolia.ts'),
    'Myanmar': os.path.join(root, 'asia', '84_myanmar.ts'),
    'Nepal': os.path.join(root, 'asia', '85_nepal.ts'),
    'Oman': os.path.join(root, 'asia', '86_oman.ts'),
    'Pakistan': os.path.join(root, 'asia', '87_pakistan.ts'),
    'Palestina': os.path.join(root, 'asia', '88_palestina.ts'),
    'Qatar': os.path.join(root, 'asia', '89_qatar.ts'),
    'Republik timor-leste': os.path.join(root, 'asia', '90_republik_timor_leste.ts'),
    'Singapura': os.path.join(root, 'asia', '91_singapura.ts'),
    'Sri lanka': os.path.join(root, 'asia', '92_sri_lanka.ts'),
    'Suriah': os.path.join(root, 'asia', '93_suriah.ts'),
    'Taiwan': os.path.join(root, 'asia', '94_taiwan.ts'),
    'Tajikistan': os.path.join(root, 'asia', '95_tajikistan.ts'),
    'Thailand': os.path.join(root, 'asia', '96_thailand.ts'),
    'Turkmenistan': os.path.join(root, 'asia', '97_turkmenistan.ts'),
    'Uni emirat arab': os.path.join(root, 'asia', '98_uni_emirat_arab.ts'),
    'Uzbekistan': os.path.join(root, 'asia', '99_uzbekistan.ts'),
    'Vietnam': os.path.join(root, 'asia', '100_vietnam.ts'),
    'Yaman': os.path.join(root, 'asia', '101_yaman.ts'),
    'Yordania': os.path.join(root, 'asia', '102_yordania.ts'),

    'Afrika Selatan': os.path.join(root, 'afrika', '1_afrika_selatan.ts'),
    'Aljazair': os.path.join(root, 'afrika', '2_aljazair.ts'),
    'Angola': os.path.join(root, 'afrika', '3_angola.ts'),
    'Benin': os.path.join(root, 'afrika', '4_benin.ts'),
    'Botswana': os.path.join(root, 'afrika', '5_botswana.ts'),
    'Burkina faso': os.path.join(root, 'afrika', '6_burkina_faso.ts'),
    'Burundi': os.path.join(root, 'afrika', '7_burundi.ts'),
    'Chad': os.path.join(root, 'afrika', '8_chad.ts'),
    'Djibouti': os.path.join(root, 'afrika', '9_djibouti.ts'),
    'Eritrea': os.path.join(root, 'afrika', '10_eritrea.ts'),
    'Eswatini': os.path.join(root, 'afrika', '11_eswatini.ts'),
    'Ethiopia': os.path.join(root, 'afrika', '12_ethiopia.ts'),
    'Gabon': os.path.join(root, 'afrika', '13_gabon.ts'),
    'Gambia': os.path.join(root, 'afrika', '14_gambia.ts'),
    'Ghana': os.path.join(root, 'afrika', '15_ghana.ts'),
    'Guinea': os.path.join(root, 'afrika', '16_guinea.ts'),
    'Guinea-bissau': os.path.join(root, 'afrika', '17_guinea_bissau.ts'),
    'Kamerun': os.path.join(root, 'afrika', '18_kamerun.ts'),
    'Kenya': os.path.join(root, 'afrika', '19_kenya.ts'),
    'Komoro': os.path.join(root, 'afrika', '20_komoro.ts'),
    'Kongo': os.path.join(root, 'afrika', '21_kongo.ts'),
    'Lesotho': os.path.join(root, 'afrika', '22_lesotho.ts'),
    'Liberia': os.path.join(root, 'afrika', '23_liberia.ts'),
    'Libya': os.path.join(root, 'afrika', '24_libya.ts'),
    'Madagaskar': os.path.join(root, 'afrika', '25_madagaskar.ts'),
    'Malawi': os.path.join(root, 'afrika', '26_malawi.ts'),
    'Mali': os.path.join(root, 'afrika', '27_mali.ts'),
    'Maroko': os.path.join(root, 'afrika', '28_maroko.ts'),
    'Mauritania': os.path.join(root, 'afrika', '29_mauritania.ts'),
    'Mauritius': os.path.join(root, 'afrika', '30_mauritius.ts'),
    'Mesir': os.path.join(root, 'afrika', '31_mesir.ts'),
    'Mozambik': os.path.join(root, 'afrika', '32_mozambik.ts'),
    'Namibia': os.path.join(root, 'afrika', '33_namibia.ts'),
    'Niger': os.path.join(root, 'afrika', '34_niger.ts'),
    'Nigeria': os.path.join(root, 'afrika', '35_nigeria.ts'),
    'Pantai gading': os.path.join(root, 'afrika', '36_pantai_gading.ts'),
    'Republik afrika tengah': os.path.join(root, 'afrika', '37_republik_afrika_tengah.ts'),
    'Republik demokratik kongo': os.path.join(root, 'afrika', '38_republik_demokratik_kongo.ts'),
    'Republik sudan': os.path.join(root, 'afrika', '39_republik_sudan.ts'),
    'Republik tanzania': os.path.join(root, 'afrika', '40_republik_tanzania.ts'),
    'Republik uganda': os.path.join(root, 'afrika', '41_republik_uganda.ts'),
    'Republik zambia': os.path.join(root, 'afrika', '42_republik_zambia.ts'),
    'Republik zimbabwe': os.path.join(root, 'afrika', '43_republik_zimbabwe.ts'),
    'Rwanda': os.path.join(root, 'afrika', '44_rwanda.ts'),
    'Sao tome dan principe': os.path.join(root, 'afrika', '45_sao_tome_dan_principe.ts'),
    'Senegal': os.path.join(root, 'afrika', '46_senegal.ts'),
    'Seychelles': os.path.join(root, 'afrika', '47_seychelles.ts'),
    'Sierra leone': os.path.join(root, 'afrika', '48_sierra_leone.ts'),
    'Somalia': os.path.join(root, 'afrika', '49_somalia.ts'),
    'Sudan selatan': os.path.join(root, 'afrika', '50_sudan_selatan.ts'),
    'Tanjung verde': os.path.join(root, 'afrika', '51_tanjung_verde.ts'),
    'Togo': os.path.join(root, 'afrika', '52_togo.ts'),
    'Tunisia': os.path.join(root, 'afrika', '53_tunisia.ts'),

    'Albania': os.path.join(root, 'eropa', '103_albania.ts'),
    'Andorra': os.path.join(root, 'eropa', '104_andorra.ts'),
    'Austria': os.path.join(root, 'eropa', '105_austria.ts'),
    'Belanda': os.path.join(root, 'eropa', '106_belanda.ts'),
    'Belarus': os.path.join(root, 'eropa', '107_belarus.ts'),
    'Belgia': os.path.join(root, 'eropa', '108_belgia.ts'),
    'Bosnia dan hercegovina': os.path.join(root, 'eropa', '109_bosnia_dan_hercegovina.ts'),
    'Bulgaria': os.path.join(root, 'eropa', '110_bulgaria.ts'),
    'Ceko': os.path.join(root, 'eropa', '111_ceko.ts'),
    'Denmark': os.path.join(root, 'eropa', '112_denmark.ts'),
    'Estonia': os.path.join(root, 'eropa', '113_estonia.ts'),
    'Finlandia': os.path.join(root, 'eropa', '114_finlandia.ts'),
    'Gibraltar': os.path.join(root, 'eropa', '115_gibraltar.ts'),
    'Hungaria': os.path.join(root, 'eropa', '116_hungaria.ts'),
    'Inggris': os.path.join(root, 'eropa', '117_inggris.ts'),
    'Irlandia': os.path.join(root, 'eropa', '118_irlandia.ts'),
    'Islandia': os.path.join(root, 'eropa', '119_islandia.ts'),
    'Italia': os.path.join(root, 'eropa', '120_italia.ts'),
    'Jerman': os.path.join(root, 'eropa', '121_jerman.ts'),
    'Kepulauan faroe': os.path.join(root, 'eropa', '122_kepulauan_faroe.ts'),
    'Kosovo': os.path.join(root, 'eropa', '123_kosovo.ts'),
    'Kroasia': os.path.join(root, 'eropa', '124_kroasia.ts'),
    'Latvia': os.path.join(root, 'eropa', '125_latvia.ts'),
    'Liechtenstein': os.path.join(root, 'eropa', '126_liechtenstein.ts'),
    'Lithuania': os.path.join(root, 'eropa', '127_lithuania.ts'),
    'Luksemburg': os.path.join(root, 'eropa', '128_luksemburg.ts'),
    'Makedonia utara': os.path.join(root, 'eropa', '129_makedonia_utara.ts'),
    'Malta': os.path.join(root, 'eropa', '130_malta.ts'),
    'Moldova': os.path.join(root, 'eropa', '131_moldova.ts'),
    'Monako': os.path.join(root, 'eropa', '132_monako.ts'),
    'Montenegro': os.path.join(root, 'eropa', '133_montenegro.ts'),
    'Norwegia': os.path.join(root, 'eropa', '134_norwegia.ts'),
    'Polandia': os.path.join(root, 'eropa', '135_polandia.ts'),
    'Portugal': os.path.join(root, 'eropa', '136_portugal.ts'),
    'Prancis': os.path.join(root, 'eropa', '137_prancis.ts'),
    'Republik rumania': os.path.join(root, 'eropa', '138_republik_rumania.ts'),
    'Republik serbia': os.path.join(root, 'eropa', '139_republik_serbia.ts'),
    'Rusia': os.path.join(root, 'eropa', '140_rusia.ts'),
    'San marino': os.path.join(root, 'eropa', '141_san_marino.ts'),
    'Siprus': os.path.join(root, 'eropa', '142_siprus.ts'),
    'Slovenia': os.path.join(root, 'eropa', '143_slovenia.ts'),
    'Slowakia': os.path.join(root, 'eropa', '144_slowakia.ts'),
    'Spanyol': os.path.join(root, 'eropa', '145_spanyol.ts'),
    'Swedia': os.path.join(root, 'eropa', '146_swedia.ts'),
    'Swiss': os.path.join(root, 'eropa', '147_swiss.ts'),
    'Turki': os.path.join(root, 'eropa', '148_turki.ts'),
    'Ukraina': os.path.join(root, 'eropa', '149_ukraina.ts'),
    'Vatikan': os.path.join(root, 'eropa', '150_vatikan.ts'),
    'Yunani': os.path.join(root, 'eropa', '151_yunani.ts'),

    'Amerika Serikat': os.path.join(root, 'na', '152_amerika_serikat.ts'),
    'Antigua dan Barbuda': os.path.join(root, 'na', '153_antigua_dan_barbuda.ts'),
    'Bahama': os.path.join(root, 'na', '154_bahama.ts'),
    'Barbados': os.path.join(root, 'na', '155_barbados.ts'),
    'Belize': os.path.join(root, 'na', '156_belize.ts'),
    'Bermuda': os.path.join(root, 'na', '157_bermuda.ts'),
    'Costa rica': os.path.join(root, 'na', '158_costa_rica.ts'),
    'Curacao': os.path.join(root, 'na', '159_curacao.ts'),
    'Dominika': os.path.join(root, 'na', '160_dominika.ts'),
    'El salvador': os.path.join(root, 'na', '161_el_salvador.ts'),
    'Greenland': os.path.join(root, 'na', '162_greenland.ts'),
    'Grenada': os.path.join(root, 'na', '163_grenada.ts'),
    'Guatemala': os.path.join(root, 'na', '164_guatemala.ts'),
    'Haiti': os.path.join(root, 'na', '165_haiti.ts'),
    'Honduras': os.path.join(root, 'na', '166_honduras.ts'),
    'Jamaika': os.path.join(root, 'na', '167_jamaika.ts'),
    'Kanada': os.path.join(root, 'na', '168_kanada.ts'),
    'Kuba': os.path.join(root, 'na', '169_kuba.ts'),
    'Meksiko': os.path.join(root, 'na', '170_meksiko.ts'),
    'Nikaragua': os.path.join(root, 'na', '171_nikaragua.ts'),
    'Panama': os.path.join(root, 'na', '172_panama.ts'),
    'Puerto rico': os.path.join(root, 'na', '173_puerto_rico.ts'),
    'Republik dominika': os.path.join(root, 'na', '174_republik_dominika.ts'),
    'Saint kitts dan nevis': os.path.join(root, 'na', '175_saint_kitts_dan_nevis.ts'),
    'Saint lucia': os.path.join(root, 'na', '176_saint_lucia.ts'),
    'Saint vincent dan grenadine': os.path.join(root, 'na', '177_saint_vincent_dan_grenadine.ts'),
    'Trinidad dan tobago': os.path.join(root, 'na', '178_trinidad_dan_tobago.ts'),

    'Australia': os.path.join(root, 'oceania', '179_australia.ts'),
    'Fiji': os.path.join(root, 'oceania', '180_fiji.ts'),
    'Guam': os.path.join(root, 'oceania', '181_guam.ts'),
    'Kiribati': os.path.join(root, 'oceania', '182_kiribati.ts'),
    'Marshall': os.path.join(root, 'oceania', '183_marshall.ts'),
    'Mikronesia': os.path.join(root, 'oceania', '184_mikronesia.ts'),
    'Nauru': os.path.join(root, 'oceania', '185_nauru.ts'),
    'Palau': os.path.join(root, 'oceania', '186_palau.ts'),
    'Papua nugini': os.path.join(root, 'oceania', '187_papua_nugini.ts'),
    'Samoa': os.path.join(root, 'oceania', '188_samoa.ts'),
    'Samoa amerika': os.path.join(root, 'oceania', '189_samoa_amerika.ts'),
    'Selandia baru': os.path.join(root, 'oceania', '190_selandia_baru.ts'),
    'Tahiti': os.path.join(root, 'oceania', '191_tahiti.ts'),
    'Tonga': os.path.join(root, 'oceania', '192_tonga.ts'),
    'Tuvalu': os.path.join(root, 'oceania', '193_tuvalu.ts'),
    'Vanuatu': os.path.join(root, 'oceania', '194_vanuatu.ts'),

    'Argentina': os.path.join(root, 'sa', '195_argentina.ts'),
    'Bolivia': os.path.join(root, 'sa', '196_bolivia.ts'),
    'Brazil': os.path.join(root, 'sa', '197_brazil.ts'),
    'Chile': os.path.join(root, 'sa', '198_chile.ts'),
    'Ekuador': os.path.join(root, 'sa', '199_ekuador.ts'),
    'Guiana prancis': os.path.join(root, 'sa', '200_guiana_prancis.ts'),
    'Guyana': os.path.join(root, 'sa', '201_guyana.ts'),
    'Kolombia': os.path.join(root, 'sa', '202_kolombia.ts'),
    'Paraguay': os.path.join(root, 'sa', '203_paraguay.ts'),
    'Peru': os.path.join(root, 'sa', '204_peru.ts'),
    'Suriname': os.path.join(root, 'sa', '205_suriname.ts'),
    'Uruguay': os.path.join(root, 'sa', '206_uruguay.ts'),
    'Venezuela': os.path.join(root, 'sa', '207_venezuela.ts'),
}

rows = [
    ('Afganistan', 600),
    ('Arab Saudi', 400),
    ('Armenia', 660),
    ('Azerbaijan', 750),
    ('Bahrain', 150),
    ('Bangladesh', 785),
    ('Bhutan', 670),
    ('Brunei', 300),
    ('China', 900),
    ('Filipina', 830),
    ('Georgia', 580),
    ('Hong kong', 315),
    ('India', 935),
    ('Indonesia', 680),
    ('Irak', 650),
    ('Iran', 740),
    ('Israel', 980),
    ('Jepang', 896),
    ('Kamboja', 550),
    ('Kazakhstan', 470),
    ('Kirgizstan', 370),
    ('Korea Selatan', 850),
    ('Korea Utara', 1150),
    ('Kuwait', 190),
    ('Laos', 590),
    ('Lebanon', 545),
    ('Makau', 240),
    ('Malaysia', 615),
    ('Maldives', 140),
    ('Mongolia', 350),
    ('Myanmar', 600),
    ('Nepal', 730),
    ('Oman', 300),
    ('Pakistan', 860),
    ('Palestina', 660),
    ('Qatar', 150),
    ('Republik timor-leste', 320),
    ('Singapura', 470),
    ('Sri lanka', 840),
    ('Suriah', 595),
    ('Taiwan', 710),
    ('Tajikistan', 630),
    ('Thailand', 670),
    ('Turkmenistan', 530),
    ('Uni emirat arab', 100),
    ('Uzbekistan', 580),
    ('Vietnam', 700),
    ('Yaman', 500),
    ('Yordania', 685),
    ('Afrika Selatan', 760),
    ('Aljazair', 950),
    ('Angola', 730),
    ('Benin', 880),
    ('Botswana', 680),
    ('Burkina faso', 905),
    ('Burundi', 960),
    ('Chad', 960),
    ('Djibouti', 730),
    ('Eritrea', 800),
    ('Eswatini', 790),
    ('Ethiopia', 870),
    ('Gabon', 1030),
    ('Gambia', 800),
    ('Ghana', 810),
    ('Guinea', 950),
    ('Guinea-bissau', 800),
    ('Kamerun', 927),
    ('Kenya', 845),
    ('Komoro', 750),
    ('Kongo', 1020),
    ('Lesotho', 790),
    ('Liberia', 695),
    ('Libya', 500),
    ('Madagaskar', 800),
    ('Malawi', 890),
    ('Mali', 930),
    ('Maroko', 990),
    ('Mauritania', 840),
    ('Mauritius', 710),
    ('Mesir', 815),
    ('Mozambik', 940),
    ('Namibia', 960),
    ('Niger', 915),
    ('Nigeria', 755),
    ('Pantai gading', 945),
    ('Republik afrika tengah', 1130),
    ('Republik demokratik kongo', 1030),
    ('Republik sudan', 840),
    ('Republik tanzania', 890),
    ('Republik uganda', 890),
    ('Republik zambia', 945),
    ('Republik zimbabwe', 907),
    ('Rwanda', 880),
    ('Sao tome dan principe', 770),
    ('Senegal', 930),
    ('Seychelles', 350),
    ('Sierra leone', 900),
    ('Somalia', 760),
    ('Sudan selatan', 680),
    ('Tanjung verde', 750),
    ('Albania', 630),
    ('Andorra', 385),
    ('Austria', 1010),
    ('Belanda', 905),
    ('Belarus', 730),
    ('Belgia', 970),
    ('Bosnia dan hercegovina', 800),
    ('Bulgaria', 670),
    ('Ceko', 725),
    ('Denmark', 1050),
    ('Estonia', 820),
    ('Finlandia', 975),
    ('Gibraltar', 500),
    ('Hungaria', 610),
    ('Inggris', 900),
    ('Irlandia', 860),
    ('Islandia', 920),
    ('Italia', 900),
    ('Jerman', 920),
    ('Kepulauan faroe', 579),
    ('Kosovo', 530),
    ('Kroasia', 800),
    ('Latvia', 830),
    ('Liechtenstein', 402),
    ('Lithuania', 730),
    ('Luksemburg', 790),
    ('Makedonia utara', 510),
    ('Malta', 880),
    ('Moldova', 550),
    ('Monako', 533),
    ('Montenegro', 590),
    ('Norwegia', 989),
    ('Polandia', 740),
    ('Portugal', 935),
    ('Prancis', 910),
    ('Republik rumania', 725),
    ('Republik serbia', 570),
    ('Rusia', 600),
    ('San marino', 770),
    ('Siprus', 635),
    ('Slovenia', 920),
    ('Slowakia', 730),
    ('Spanyol', 920),
    ('Swedia', 1046),
    ('Swiss', 669),
    ('Turki', 830),
    ('Ukraina', 610),
    ('Vatikan', 990),
    ('Yunani', 910),
    ('Amerika Serikat', 605),
    ('Antigua dan Barbuda', 450),
    ('Bahama', 175),
    ('Barbados', 800),
    ('Belize', 675),
    ('Bermuda', 210),
    ('Costa rica', 740),
    ('Curacao', 930),
    ('Dominika', 770),
    ('El salvador', 780),
    ('Greenland', 598),
    ('Grenada', 775),
    ('Guatemala', 790),
    ('Haiti', 750),
    ('Honduras', 770),
    ('Jamaika', 775),
    ('Kanada', 860),
    ('Kuba', 1250),
    ('Meksiko', 870),
    ('Nikaragua', 800),
    ('Panama', 370),
    ('Puerto rico', 745),
    ('Republik dominika', 825),
    ('Saint kitts dan nevis', 470),
    ('Saint lucia', 775),
    ('Saint vincent dan grenadine', 775),
    ('Trinidad dan tobago', 775),
    ('Argentina', 1060),
    ('Bolivia', 830),
    ('Brazil', 845),
    ('Chile', 930),
    ('Ekuador', 820),
    ('Guiana prancis', 910),
    ('Guyana', 775),
    ('Kolombia', 960),
    ('Paraguay', 650),
    ('Peru', 830),
    ('Suriname', 760),
    ('Uruguay', 830),
    ('Venezuela', 920),
    ('Australia', 880),
    ('Fiji', 660),
    ('Guam', 780),
    ('Kiribati', 600),
    ('Marshall', 750),
    ('Mikronesia', 800),
    ('Nauru', 50),
    ('Palau', 700),
    ('Papua nugini', 870),
    ('Samoa', 770),
    ('Samoa amerika', 780),
    ('Selandia baru', 900),
    ('Tahiti', 775),
    ('Tonga', 750),
    ('Tuvalu', 600),
    ('Vanuatu', 300),
]

for country, value in rows:
    path_file = mapping.get(country)
    if not path_file or not os.path.exists(path_file):
        print('missing', country, path_file)
        continue
    with open(path_file, 'r', encoding='utf-8') as fh:
        content = fh.read()
    new_content = re.sub(r'(\bemas\s*:\s*)(\d+)', rf'\g<1>{int(value)}', content, count=1)
    if new_content != content:
        with open(path_file, 'w', encoding='utf-8') as fh:
            fh.write(new_content)
        print('updated', country, value)
