import os, re
from pathlib import Path

root = Path(r'c:\utama\project\project-sendiri\EM\json\semua_fitur_negara\1_pembangunan\1_produksi\2_sektor_mineral_kritis')

files = {
    'Afganistan': root / 'asia' / '54_afganistan.ts',
    'Arab Saudi': root / 'asia' / '55_arab_saudi.ts',
    'Armenia': root / 'asia' / '56_armenia.ts',
    'Azerbaijan': root / 'asia' / '57_azerbaijan.ts',
    'Bahrain': root / 'asia' / '58_bahrain.ts',
    'Bangladesh': root / 'asia' / '59_bangladesh.ts',
    'Bhutan': root / 'asia' / '60_bhutan.ts',
    'Brunei': root / 'asia' / '61_brunei.ts',
    'China': root / 'asia' / '62_china.ts',
    'Filipina': root / 'asia' / '63_filipina.ts',
    'Georgia': root / 'asia' / '64_georgia.ts',
    'Hong kong': root / 'asia' / '65_hong_kong.ts',
    'India': root / 'asia' / '66_india.ts',
    'Indonesia': root / 'asia' / '67_indonesia.ts',
    'Irak': root / 'asia' / '68_irak.ts',
    'Iran': root / 'asia' / '69_iran.ts',
    'Israel': root / 'asia' / '70_israel.ts',
    'Jepang': root / 'asia' / '71_jepang.ts',
    'Kamboja': root / 'asia' / '72_kamboja.ts',
    'Kazakhstan': root / 'asia' / '73_kazakhstan.ts',
    'Kirgizstan': root / 'asia' / '74_kirgizstan.ts',
    'Korea Selatan': root / 'asia' / '75_korea_selatan.ts',
    'Korea Utara': root / 'asia' / '76_korea_utara.ts',
    'Kuwait': root / 'asia' / '77_kuwait.ts',
    'Laos': root / 'asia' / '78_laos.ts',
    'Lebanon': root / 'asia' / '79_lebanon.ts',
    'Makau': root / 'asia' / '80_makau.ts',
    'Malaysia': root / 'asia' / '81_malaysia.ts',
    'Maldives': root / 'asia' / '82_maldives.ts',
    'Mongolia': root / 'asia' / '83_mongolia.ts',
    'Myanmar': root / 'asia' / '84_myanmar.ts',
    'Nepal': root / 'asia' / '85_nepal.ts',
    'Oman': root / 'asia' / '86_oman.ts',
    'Pakistan': root / 'asia' / '87_pakistan.ts',
    'Palestina': root / 'asia' / '88_palestina.ts',
    'Qatar': root / 'asia' / '89_qatar.ts',
    'Republik timor-leste': root / 'asia' / '90_republik_timor_leste.ts',
    'Singapura': root / 'asia' / '91_singapura.ts',
    'Sri lanka': root / 'asia' / '92_sri_lanka.ts',
    'Suriah': root / 'asia' / '93_suriah.ts',
    'Taiwan': root / 'asia' / '94_taiwan.ts',
    'Tajikistan': root / 'asia' / '95_tajikistan.ts',
    'Thailand': root / 'asia' / '96_thailand.ts',
    'Turkmenistan': root / 'asia' / '97_turkmenistan.ts',
    'Uni emirat arab': root / 'asia' / '98_uni_emirat_arab.ts',
    'Uzbekistan': root / 'asia' / '99_uzbekistan.ts',
    'Vietnam': root / 'asia' / '100_vietnam.ts',
    'Yaman': root / 'asia' / '101_yaman.ts',
    'Yordania': root / 'asia' / '102_yordania.ts',

    'Afrika Selatan': root / 'afrika' / '1_afrika_selatan.ts',
    'Aljazair': root / 'afrika' / '2_aljazair.ts',
    'Angola': root / 'afrika' / '3_angola.ts',
    'Benin': root / 'afrika' / '4_benin.ts',
    'Botswana': root / 'afrika' / '5_botswana.ts',
    'Burkina faso': root / 'afrika' / '6_burkina_faso.ts',
    'Burundi': root / 'afrika' / '7_burundi.ts',
    'Chad': root / 'afrika' / '8_chad.ts',
    'Djibouti': root / 'afrika' / '9_djibouti.ts',
    'Eritrea': root / 'afrika' / '10_eritrea.ts',
    'Eswatini': root / 'afrika' / '11_eswatini.ts',
    'Ethiopia': root / 'afrika' / '12_ethiopia.ts',
    'Gabon': root / 'afrika' / '13_gabon.ts',
    'Gambia': root / 'afrika' / '14_gambia.ts',
    'Ghana': root / 'afrika' / '15_ghana.ts',
    'Guinea': root / 'afrika' / '16_guinea.ts',
    'Guinea-bissau': root / 'afrika' / '17_guinea_bissau.ts',
    'Kamerun': root / 'afrika' / '18_kamerun.ts',
    'Kenya': root / 'afrika' / '19_kenya.ts',
    'Komoro': root / 'afrika' / '20_komoro.ts',
    'Kongo': root / 'afrika' / '21_kongo.ts',
    'Lesotho': root / 'afrika' / '22_lesotho.ts',
    'Liberia': root / 'afrika' / '23_liberia.ts',
    'Libya': root / 'afrika' / '24_libya.ts',
    'Madagaskar': root / 'afrika' / '25_madagaskar.ts',
    'Malawi': root / 'afrika' / '26_malawi.ts',
    'Mali': root / 'afrika' / '27_mali.ts',
    'Maroko': root / 'afrika' / '28_maroko.ts',
    'Mauritania': root / 'afrika' / '29_mauritania.ts',
    'Mauritius': root / 'afrika' / '30_mauritius.ts',
    'Mesir': root / 'afrika' / '31_mesir.ts',
    'Mozambik': root / 'afrika' / '32_mozambik.ts',
    'Namibia': root / 'afrika' / '33_namibia.ts',
    'Niger': root / 'afrika' / '34_niger.ts',
    'Nigeria': root / 'afrika' / '35_nigeria.ts',
    'Pantai gading': root / 'afrika' / '36_pantai_gading.ts',
    'Republik afrika tengah': root / 'afrika' / '37_republik_afrika_tengah.ts',
    'Republik demokratik kongo': root / 'afrika' / '38_republik_demokratik_kongo.ts',
    'Republik sudan': root / 'afrika' / '39_republik_sudan.ts',
    'Republik tanzania': root / 'afrika' / '40_republik_tanzania.ts',
    'Republik uganda': root / 'afrika' / '41_republik_uganda.ts',
    'Republik zambia': root / 'afrika' / '42_republik_zambia.ts',
    'Republik zimbabwe': root / 'afrika' / '43_republik_zimbabwe.ts',
    'Rwanda': root / 'afrika' / '44_rwanda.ts',
    'Sao tome dan principe': root / 'afrika' / '45_sao_tome_dan_principe.ts',
    'Senegal': root / 'afrika' / '46_senegal.ts',
    'Seychelles': root / 'afrika' / '47_seychelles.ts',
    'Sierra leone': root / 'afrika' / '48_sierra_leone.ts',
    'Somalia': root / 'afrika' / '49_somalia.ts',
    'Sudan selatan': root / 'afrika' / '50_sudan_selatan.ts',
    'Tanjung verde': root / 'afrika' / '51_tanjung_verde.ts',
    'Togo': root / 'afrika' / '52_togo.ts',
    'Tunisia': root / 'afrika' / '53_tunisia.ts',
    'Albania': root / 'eropa' / '103_albania.ts',
    'Andorra': root / 'eropa' / '104_andorra.ts',
    'Austria': root / 'eropa' / '105_austria.ts',
    'Belanda': root / 'eropa' / '106_belanda.ts',
    'Belarus': root / 'eropa' / '107_belarus.ts',
    'Belgia': root / 'eropa' / '108_belgia.ts',
    'Bosnia dan hercegovina': root / 'eropa' / '109_bosnia_dan_hercegovina.ts',
    'Bulgaria': root / 'eropa' / '110_bulgaria.ts',
    'Ceko': root / 'eropa' / '111_ceko.ts',
    'Denmark': root / 'eropa' / '112_denmark.ts',
    'Estonia': root / 'eropa' / '113_estonia.ts',
    'Finlandia': root / 'eropa' / '114_finlandia.ts',
    'Gibraltar': root / 'eropa' / '115_gibraltar.ts',
    'Hungaria': root / 'eropa' / '116_hungaria.ts',
    'Inggris': root / 'eropa' / '117_inggris.ts',
    'Irlandia': root / 'eropa' / '118_irlandia.ts',
    'Islandia': root / 'eropa' / '119_islandia.ts',
    'Italia': root / 'eropa' / '120_italia.ts',
    'Jerman': root / 'eropa' / '121_jerman.ts',
    'Kepulauan faroe': root / 'eropa' / '122_kepulauan_faroe.ts',
    'Kosovo': root / 'eropa' / '123_kosovo.ts',
    'Kroasia': root / 'eropa' / '124_kroasia.ts',
    'Latvia': root / 'eropa' / '125_latvia.ts',
    'Liechtenstein': root / 'eropa' / '126_liechtenstein.ts',
    'Lithuania': root / 'eropa' / '127_lithuania.ts',
    'Luksemburg': root / 'eropa' / '128_luksemburg.ts',
    'Makedonia utara': root / 'eropa' / '129_makedonia_utara.ts',
    'Malta': root / 'eropa' / '130_malta.ts',
    'Moldova': root / 'eropa' / '131_moldova.ts',
    'Monako': root / 'eropa' / '132_monako.ts',
    'Montenegro': root / 'eropa' / '133_montenegro.ts',
    'Norwegia': root / 'eropa' / '134_norwegia.ts',
    'Polandia': root / 'eropa' / '135_polandia.ts',
    'Portugal': root / 'eropa' / '136_portugal.ts',
    'Prancis': root / 'eropa' / '137_prancis.ts',
    'Republik rumania': root / 'eropa' / '138_republik_rumania.ts',
    'Republik serbia': root / 'eropa' / '139_republik_serbia.ts',
    'Rusia': root / 'eropa' / '140_rusia.ts',
    'San marino': root / 'eropa' / '141_san_marino.ts',
    'Siprus': root / 'eropa' / '142_siprus.ts',
    'Slovenia': root / 'eropa' / '143_slovenia.ts',
    'Slowakia': root / 'eropa' / '144_slowakia.ts',
    'Spanyol': root / 'eropa' / '145_spanyol.ts',
    'Swedia': root / 'eropa' / '146_swedia.ts',
    'Swiss': root / 'eropa' / '147_swiss.ts',
    'Turki': root / 'eropa' / '148_turki.ts',
    'Ukraina': root / 'eropa' / '149_ukraina.ts',
    'Vatikan': root / 'eropa' / '150_vatikan.ts',
    'Yunani': root / 'eropa' / '151_yunani.ts',

    'Amerika Serikat': root / 'na' / '152_amerika_serikat.ts',
    'Antigua dan Barbuda': root / 'na' / '153_antigua_dan_barbuda.ts',
    'Bahama': root / 'na' / '154_bahama.ts',
    'Barbados': root / 'na' / '155_barbados.ts',
    'Belize': root / 'na' / '156_belize.ts',
    'Bermuda': root / 'na' / '157_bermuda.ts',
    'Costa rica': root / 'na' / '158_costa_rica.ts',
    'Curacao': root / 'na' / '159_curacao.ts',
    'Dominika': root / 'na' / '160_dominika.ts',
    'El salvador': root / 'na' / '161_el_salvador.ts',
    'Greenland': root / 'na' / '162_greenland.ts',
    'Grenada': root / 'na' / '163_grenada.ts',
    'Guatemala': root / 'na' / '164_guatemala.ts',
    'Haiti': root / 'na' / '165_haiti.ts',
    'Honduras': root / 'na' / '166_honduras.ts',
    'Jamaika': root / 'na' / '167_jamaika.ts',
    'Kanada': root / 'na' / '168_kanada.ts',
    'Kuba': root / 'na' / '169_kuba.ts',
    'Meksiko': root / 'na' / '170_meksiko.ts',
    'Nikaragua': root / 'na' / '171_nikaragua.ts',
    'Panama': root / 'na' / '172_panama.ts',
    'Puerto rico': root / 'na' / '173_puerto_rico.ts',
    'Republik dominika': root / 'na' / '174_republik_dominika.ts',
    'Saint kitts dan nevis': root / 'na' / '175_saint_kitts_dan_nevis.ts',
    'Saint lucia': root / 'na' / '176_saint_lucia.ts',
    'Saint vincent dan grenadine': root / 'na' / '177_saint_vincent_dan_grenadine.ts',
    'Trinidad dan tobago': root / 'na' / '178_trinidad_dan_tobago.ts',

    'Australia': root / 'oceania' / '179_australia.ts',
    'Fiji': root / 'oceania' / '180_fiji.ts',
    'Guam': root / 'oceania' / '181_guam.ts',
    'Kiribati': root / 'oceania' / '182_kiribati.ts',
    'Marshall': root / 'oceania' / '183_marshall.ts',
    'Mikronesia': root / 'oceania' / '184_mikronesia.ts',
    'Nauru': root / 'oceania' / '185_nauru.ts',
    'Palau': root / 'oceania' / '186_palau.ts',
    'Papua nugini': root / 'oceania' / '187_papua_nugini.ts',
    'Samoa': root / 'oceania' / '188_samoa.ts',
    'Samoa amerika': root / 'oceania' / '189_samoa_amerika.ts',
    'Selandia baru': root / 'oceania' / '190_selandia_baru.ts',
    'Tahiti': root / 'oceania' / '191_tahiti.ts',
    'Tonga': root / 'oceania' / '192_tonga.ts',
    'Tuvalu': root / 'oceania' / '193_tuvalu.ts',
    'Vanuatu': root / 'oceania' / '194_vanuatu.ts',

    'Argentina': root / 'sa' / '195_argentina.ts',
    'Bolivia': root / 'sa' / '196_bolivia.ts',
    'Brazil': root / 'sa' / '197_brazil.ts',
    'Chile': root / 'sa' / '198_chile.ts',
    'Ekuador': root / 'sa' / '199_ekuador.ts',
    'Guiana prancis': root / 'sa' / '200_guiana_prancis.ts',
    'Guyana': root / 'sa' / '201_guyana.ts',
    'Kolombia': root / 'sa' / '202_kolombia.ts',
    'Paraguay': root / 'sa' / '203_paraguay.ts',
    'Peru': root / 'sa' / '204_peru.ts',
    'Suriname': root / 'sa' / '205_suriname.ts',
    'Uruguay': root / 'sa' / '206_uruguay.ts',
    'Venezuela': root / 'sa' / '207_venezuela.ts',
}

values = {
    'Afganistan': 600,
    'Arab Saudi': 400,
    'Armenia': 660,
    'Azerbaijan': 750,
    'Bahrain': 150,
    'Bangladesh': 785,
    'Bhutan': 670,
    'Brunei': 300,
    'China': 900,
    'Filipina': 830,
    'Georgia': 580,
    'Hong kong': 315,
    'India': 935,
    'Indonesia': 680,
    'Irak': 650,
    'Iran': 740,
    'Israel': 980,
    'Jepang': 896,
    'Kamboja': 550,
    'Kazakhstan': 470,
    'Kirgizstan': 370,
    'Korea Selatan': 850,
    'Korea Utara': 1150,
    'Kuwait': 190,
    'Laos': 590,
    'Lebanon': 545,
    'Makau': 240,
    'Malaysia': 615,
    'Maldives': 140,
    'Mongolia': 350,
    'Myanmar': 600,
    'Nepal': 730,
    'Oman': 300,
    'Pakistan': 860,
    'Palestina': 660,
    'Qatar': 150,
    'Republik timor-leste': 320,
    'Singapura': 470,
    'Sri lanka': 840,
    'Suriah': 595,
    'Taiwan': 710,
    'Tajikistan': 630,
    'Thailand': 670,
    'Turkmenistan': 530,
    'Uni emirat arab': 100,
    'Uzbekistan': 580,
    'Vietnam': 700,
    'Yaman': 500,
    'Yordania': 685,
    'Afrika Selatan': 760,
    'Aljazair': 950,
    'Angola': 730,
    'Benin': 880,
    'Botswana': 680,
    'Burkina faso': 905,
    'Burundi': 960,
    'Chad': 960,
    'Djibouti': 730,
    'Eritrea': 800,
    'Eswatini': 790,
    'Ethiopia': 870,
    'Gabon': 1030,
    'Gambia': 800,
    'Ghana': 810,
    'Guinea': 950,
    'Guinea-bissau': 800,
    'Kamerun': 927,
    'Kenya': 845,
    'Komoro': 750,
    'Kongo': 1020,
    'Lesotho': 790,
    'Liberia': 695,
    'Libya': 500,
    'Madagaskar': 800,
    'Malawi': 890,
    'Mali': 930,
    'Maroko': 990,
    'Mauritania': 840,
    'Mauritius': 710,
    'Mesir': 815,
    'Mozambik': 940,
    'Namibia': 960,
    'Niger': 915,
    'Nigeria': 755,
    'Pantai gading': 945,
    'Republik afrika tengah': 1130,
    'Republik demokratik kongo': 1030,
    'Republik sudan': 840,
    'Republik tanzania': 890,
    'Republik uganda': 890,
    'Republik zambia': 945,
    'Republik zimbabwe': 907,
    'Rwanda': 880,
    'Sao tome dan principe': 770,
    'Senegal': 930,
    'Seychelles': 350,
    'Sierra leone': 900,
    'Somalia': 760,
    'Sudan selatan': 680,
    'Tanjung verde': 750,
    'Albania': 630,
    'Andorra': 385,
    'Austria': 1010,
    'Belanda': 905,
    'Belarus': 730,
    'Belgia': 970,
    'Bosnia dan hercegovina': 800,
    'Bulgaria': 670,
    'Ceko': 725,
    'Denmark': 1050,
    'Estonia': 820,
    'Finlandia': 975,
    'Gibraltar': 500,
    'Hungaria': 610,
    'Inggris': 900,
    'Irlandia': 860,
    'Islandia': 920,
    'Italia': 900,
    'Jerman': 920,
    'Kepulauan faroe': 579,
    'Kosovo': 530,
    'Kroasia': 800,
    'Latvia': 830,
    'Liechtenstein': 402,
    'Lithuania': 730,
    'Luksemburg': 790,
    'Makedonia utara': 510,
    'Malta': 880,
    'Moldova': 550,
    'Monako': 533,
    'Montenegro': 590,
    'Norwegia': 989,
    'Polandia': 740,
    'Portugal': 935,
    'Prancis': 910,
    'Republik rumania': 725,
    'Republik serbia': 570,
    'Rusia': 600,
    'San marino': 770,
    'Siprus': 635,
    'Slovenia': 920,
    'Slowakia': 730,
    'Spanyol': 920,
    'Swedia': 1046,
    'Swiss': 669,
    'Turki': 830,
    'Ukraina': 610,
    'Vatikan': 990,
    'Yunani': 910,
    'Amerika Serikat': 605,
    'Antigua dan Barbuda': 450,
    'Bahama': 175,
    'Barbados': 800,
    'Belize': 675,
    'Bermuda': 210,
    'Costa rica': 740,
    'Curacao': 930,
    'Dominika': 770,
    'El salvador': 780,
    'Greenland': 598,
    'Grenada': 775,
    'Guatemala': 790,
    'Haiti': 750,
    'Honduras': 770,
    'Jamaika': 775,
    'Kanada': 860,
    'Kuba': 1250,
    'Meksiko': 870,
    'Nikaragua': 800,
    'Panama': 370,
    'Puerto rico': 745,
    'Republik dominika': 825,
    'Saint kitts dan nevis': 470,
    'Saint lucia': 775,
    'Saint vincent dan grenadine': 775,
    'Trinidad dan tobago': 775,
    'Argentina': 1060,
    'Bolivia': 830,
    'Brazil': 845,
    'Chile': 930,
    'Ekuador': 820,
    'Guiana prancis': 910,
    'Guyana': 775,
    'Kolombia': 960,
    'Paraguay': 650,
    'Peru': 830,
    'Suriname': 760,
    'Uruguay': 830,
    'Venezuela': 920,
    'Australia': 880,
    'Fiji': 660,
    'Guam': 780,
    'Kiribati': 600,
    'Marshall': 750,
    'Mikronesia': 800,
    'Nauru': 50,
    'Palau': 700,
    'Papua nugini': 870,
    'Samoa': 770,
    'Samoa amerika': 780,
    'Selandia baru': 900,
    'Tahiti': 775,
    'Tonga': 750,
    'Tuvalu': 600,
    'Vanuatu': 300,
}

for country, path in files.items():
    if country not in values:
        continue
    if not path.exists():
        continue
    text = path.read_text(encoding='utf-8')
    new_text = re.sub(r'(\bemas\s*:\s*)(\d+)', rf'\g<1>{values[country]}', text, count=1)
    if new_text != text:
        path.write_text(new_text, encoding='utf-8')
        print(f'updated {country} -> {values[country]}')
