const fs = require('fs');
const path = require('path');

// Mineral data (excluding emas)
const mineralData = [
  {
    "country": "Afganistan",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Arab Saudi",
    "nikel": 0,
    "bijah_besi": 3,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 2,
    "batu_bara": 0,
    "minyak_bumi": 130,
    "gas_alam": 70,
    "uranium": 0,
    "garam": 5
  },
  {
    "country": "Armenia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Azerbaijan",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 3,
    "gas_alam": 5,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Bahrain",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 2,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Bangladesh",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 1,
    "minyak_bumi": 0,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Bhutan",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Brunei",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 2,
    "gas_alam": 4,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "China",
    "nikel": 20,
    "bijah_besi": 70,
    "litium": 20,
    "logam_tanah_jarang": 44,
    "aluminium": 100,
    "tembaga": 50,
    "batu_bara": 100,
    "minyak_bumi": 50,
    "gas_alam": 65,
    "uranium": 10,
    "garam": 120
  },
  {
    "country": "Filipina",
    "nikel": 70,
    "bijah_besi": 5,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 2,
    "tembaga": 20,
    "batu_bara": 4,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 2
  },
  {
    "country": "Georgia",
    "nikel": 0,
    "bijah_besi": 2,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Hong kong",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "India",
    "nikel": 5,
    "bijah_besi": 50,
    "litium": 5,
    "logam_tanah_jarang": 7,
    "aluminium": 40,
    "tembaga": 10,
    "batu_bara": 80,
    "minyak_bumi": 20,
    "gas_alam": 15,
    "uranium": 3,
    "garam": 90
  },
  {
    "country": "Indonesia",
    "nikel": 135,
    "bijah_besi": 10,
    "litium": 1,
    "logam_tanah_jarang": 1,
    "aluminium": 50,
    "tembaga": 35,
    "batu_bara": 50,
    "minyak_bumi": 30,
    "gas_alam": 20,
    "uranium": 0,
    "garam": 10
  },
  {
    "country": "Irak",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 80,
    "gas_alam": 40,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Iran",
    "nikel": 1,
    "bijah_besi": 5,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 3,
    "tembaga": 5,
    "batu_bara": 3,
    "minyak_bumi": 100,
    "gas_alam": 100,
    "uranium": 2,
    "garam": 5
  },
  {
    "country": "Israel",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 3,
    "uranium": 0,
    "garam": 2
  },
  {
    "country": "Jepang",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 5
  },
  {
    "country": "Kamboja",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Kazakhstan",
    "nikel": 5,
    "bijah_besi": 10,
    "litium": 1,
    "logam_tanah_jarang": 0,
    "aluminium": 5,
    "tembaga": 10,
    "batu_bara": 25,
    "minyak_bumi": 50,
    "gas_alam": 20,
    "uranium": 40,
    "garam": 5
  },
  {
    "country": "Kirgizstan",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Korea Selatan",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 2
  },
  {
    "country": "Korea Utara",
    "nikel": 0,
    "bijah_besi": 2,
    "litium": 0,
    "logam_tanah_jarang": 1,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 5,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 2,
    "garam": 1
  },
  {
    "country": "Kuwait",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 60,
    "gas_alam": 30,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Laos",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 2,
    "batu_bara": 1,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Lebanon",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Makau",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Malaysia",
    "nikel": 1,
    "bijah_besi": 5,
    "litium": 0,
    "logam_tanah_jarang": 1,
    "aluminium": 5,
    "tembaga": 2,
    "batu_bara": 2,
    "minyak_bumi": 5,
    "gas_alam": 10,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Maldives",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Mongolia",
    "nikel": 0,
    "bijah_besi": 5,
    "litium": 0,
    "logam_tanah_jarang": 1,
    "aluminium": 0,
    "tembaga": 10,
    "batu_bara": 10,
    "minyak_bumi": 1,
    "gas_alam": 0,
    "uranium": 3,
    "garam": 1
  },
  {
    "country": "Myanmar",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 2,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 3,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Nepal",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Oman",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 2,
    "batu_bara": 0,
    "minyak_bumi": 15,
    "gas_alam": 10,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Pakistan",
    "nikel": 0,
    "bijah_besi": 2,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 5,
    "batu_bara": 5,
    "minyak_bumi": 1,
    "gas_alam": 3,
    "uranium": 0,
    "garam": 3
  },
  {
    "country": "Palestina",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Qatar",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 15,
    "gas_alam": 95,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Republik timor-leste",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Singapura",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Sri lanka",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Suriah",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 3,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Taiwan",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Tajikistan",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 2,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Thailand",
    "nikel": 0,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 1,
    "aluminium": 2,
    "tembaga": 1,
    "batu_bara": 5,
    "minyak_bumi": 2,
    "gas_alam": 4,
    "uranium": 0,
    "garam": 5
  },
  {
    "country": "Turkmenistan",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 5,
    "gas_alam": 80,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Uni emirat arab",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 5,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 70,
    "gas_alam": 35,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Uzbekistan",
    "nikel": 0,
    "bijah_besi": 2,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 5,
    "batu_bara": 5,
    "minyak_bumi": 2,
    "gas_alam": 10,
    "uranium": 15,
    "garam": 1
  },
  {
    "country": "Vietnam",
    "nikel": 2,
    "bijah_besi": 5,
    "litium": 0,
    "logam_tanah_jarang": 22,
    "aluminium": 10,
    "tembaga": 5,
    "batu_bara": 10,
    "minyak_bumi": 5,
    "gas_alam": 5,
    "uranium": 0,
    "garam": 5
  },
  {
    "country": "Yaman",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Yordania",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 1,
    "garam": 1
  },
  {
    "country": "Afrika Selatan",
    "nikel": 10,
    "bijah_besi": 25,
    "litium": 0,
    "logam_tanah_jarang": 1,
    "aluminium": 1,
    "tembaga": 5,
    "batu_bara": 30,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 2,
    "garam": 5
  },
  {
    "country": "Aljazair",
    "nikel": 0,
    "bijah_besi": 5,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 40,
    "gas_alam": 30,
    "uranium": 0,
    "garam": 2
  },
  {
    "country": "Angola",
    "nikel": 0,
    "bijah_besi": 2,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 20,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Benin",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Botswana",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 2,
    "batu_bara": 2,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 1,
    "garam": 0
  },
  {
    "country": "Burkina faso",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Burundi",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 1,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Chad",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 2,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Djibouti",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Eritrea",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Eswatini",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Ethiopia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Gabon",
    "nikel": 0,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 5,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Gambia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Ghana",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 2,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Guinea",
    "nikel": 0,
    "bijah_besi": 5,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 70,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Guinea-bissau",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Kamerun",
    "nikel": 0,
    "bijah_besi": 2,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 2,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Kenya",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Komoro",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Kongo",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 5,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Lesotho",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Liberia",
    "nikel": 0,
    "bijah_besi": 5,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Libya",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 35,
    "gas_alam": 10,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Madagaskar",
    "nikel": 5,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 1,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Malawi",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 1,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Mali",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Maroko",
    "nikel": 0,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 5
  },
  {
    "country": "Mauritania",
    "nikel": 0,
    "bijah_besi": 10,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Mauritius",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Mesir",
    "nikel": 0,
    "bijah_besi": 2,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 10,
    "gas_alam": 15,
    "uranium": 0,
    "garam": 5
  },
  {
    "country": "Mozambik",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 2,
    "minyak_bumi": 0,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Namibia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 30,
    "garam": 1
  },
  {
    "country": "Niger",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 0,
    "uranium": 25,
    "garam": 0
  },
  {
    "country": "Nigeria",
    "nikel": 0,
    "bijah_besi": 2,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 2,
    "minyak_bumi": 40,
    "gas_alam": 30,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Pantai gading",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Republik afrika tengah",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Republik demokratik kongo",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 30,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Republik sudan",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 2,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Republik tanzania",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 1,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Republik uganda",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Republik zambia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 20,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Republik zimbabwe",
    "nikel": 1,
    "bijah_besi": 2,
    "litium": 10,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 5,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Rwanda",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Sao tome dan principe",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Senegal",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Seychelles",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Sierra leone",
    "nikel": 0,
    "bijah_besi": 5,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Somalia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Sudan selatan",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 2,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Tanjung verde",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Albania",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Andorra",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Austria",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Belanda",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 5,
    "uranium": 0,
    "garam": 2
  },
  {
    "country": "Belarus",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Belgia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Bosnia dan hercegovina",
    "nikel": 0,
    "bijah_besi": 2,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 0,
    "batu_bara": 2,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Bulgaria",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 2,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Ceko",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 5,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Denmark",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 2,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Estonia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Finlandia",
    "nikel": 5,
    "bijah_besi": 0,
    "litium": 1,
    "logam_tanah_jarang": 1,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Gibraltar",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Hungaria",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Inggris",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 2,
    "minyak_bumi": 10,
    "gas_alam": 10,
    "uranium": 0,
    "garam": 30
  },
  {
    "country": "Irlandia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Islandia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Italia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 2,
    "gas_alam": 3,
    "uranium": 0,
    "garam": 5
  },
  {
    "country": "Jerman",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 15,
    "minyak_bumi": 2,
    "gas_alam": 3,
    "uranium": 0,
    "garam": 80
  },
  {
    "country": "Kepulauan faroe",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Kosovo",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 1,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Kroasia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 2
  },
  {
    "country": "Latvia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Liechtenstein",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Lithuania",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Luksemburg",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Makedonia utara",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Malta",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Moldova",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Monako",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Montenegro",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 1,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Norwegia",
    "nikel": 0,
    "bijah_besi": 2,
    "litium": 1,
    "logam_tanah_jarang": 1,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 20,
    "gas_alam": 50,
    "uranium": 0,
    "garam": 5
  },
  {
    "country": "Polandia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 10,
    "batu_bara": 20,
    "minyak_bumi": 1,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 10
  },
  {
    "country": "Portugal",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 5,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Prancis",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 2
  },
  {
    "country": "Republik rumania",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Republik serbia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 2,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Rusia",
    "nikel": 50,
    "bijah_besi": 40,
    "litium": 5,
    "logam_tanah_jarang": 21,
    "aluminium": 15,
    "tembaga": 15,
    "batu_bara": 40,
    "minyak_bumi": 120,
    "gas_alam": 105,
    "uranium": 20,
    "garam": 40
  },
  {
    "country": "San marino",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Siprus",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Slovenia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Slowakia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 1,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Spanyol",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 3
  },
  {
    "country": "Swedia",
    "nikel": 2,
    "bijah_besi": 10,
    "litium": 1,
    "logam_tanah_jarang": 1,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Swiss",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Turki",
    "nikel": 0,
    "bijah_besi": 5,
    "litium": 0,
    "logam_tanah_jarang": 1,
    "aluminium": 2,
    "tembaga": 2,
    "batu_bara": 10,
    "minyak_bumi": 2,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 5
  },
  {
    "country": "Ukraina",
    "nikel": 0,
    "bijah_besi": 30,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 2,
    "tembaga": 2,
    "batu_bara": 10,
    "minyak_bumi": 2,
    "gas_alam": 5,
    "uranium": 5,
    "garam": 5
  },
  {
    "country": "Vatikan",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Yunani",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 1,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Amerika Serikat",
    "nikel": 5,
    "bijah_besi": 20,
    "litium": 5,
    "logam_tanah_jarang": 2,
    "aluminium": 2,
    "tembaga": 40,
    "batu_bara": 70,
    "minyak_bumi": 110,
    "gas_alam": 90,
    "uranium": 10,
    "garam": 100
  },
  {
    "country": "Antigua dan Barbuda",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Bahama",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Barbados",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Belize",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Bermuda",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Costa rica",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Curacao",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Dominika",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "El salvador",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Greenland",
    "nikel": 0,
    "bijah_besi": 2,
    "litium": 0,
    "logam_tanah_jarang": 2,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Grenada",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Guatemala",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Haiti",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Honduras",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Jamaika",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 30,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Kanada",
    "nikel": 25,
    "bijah_besi": 20,
    "litium": 3,
    "logam_tanah_jarang": 1,
    "aluminium": 5,
    "tembaga": 10,
    "batu_bara": 10,
    "minyak_bumi": 30,
    "gas_alam": 60,
    "uranium": 35,
    "garam": 60
  },
  {
    "country": "Kuba",
    "nikel": 30,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Meksiko",
    "nikel": 0,
    "bijah_besi": 5,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 15,
    "batu_bara": 5,
    "minyak_bumi": 25,
    "gas_alam": 15,
    "uranium": 0,
    "garam": 45
  },
  {
    "country": "Nikaragua",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Panama",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Puerto rico",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Republik dominika",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Saint kitts dan nevis",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Saint lucia",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Saint vincent dan grenadine",
    "nikel": 1,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 1,
    "tembaga": 1,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Trinidad dan tobago",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 5,
    "gas_alam": 10,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Argentina",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 20,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 5,
    "batu_bara": 0,
    "minyak_bumi": 10,
    "gas_alam": 10,
    "uranium": 0,
    "garam": 15
  },
  {
    "country": "Bolivia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 5,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 5,
    "uranium": 0,
    "garam": 2
  },
  {
    "country": "Brazil",
    "nikel": 15,
    "bijah_besi": 80,
    "litium": 15,
    "logam_tanah_jarang": 21,
    "aluminium": 80,
    "tembaga": 5,
    "batu_bara": 5,
    "minyak_bumi": 15,
    "gas_alam": 10,
    "uranium": 5,
    "garam": 50
  },
  {
    "country": "Chile",
    "nikel": 0,
    "bijah_besi": 5,
    "litium": 25,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 90,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 50
  },
  {
    "country": "Ekuador",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 5,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Guiana prancis",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Guyana",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Kolombia",
    "nikel": 15,
    "bijah_besi": 1,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 5,
    "batu_bara": 10,
    "minyak_bumi": 10,
    "gas_alam": 5,
    "uranium": 0,
    "garam": 2
  },
  {
    "country": "Paraguay",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Peru",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 75,
    "batu_bara": 0,
    "minyak_bumi": 2,
    "gas_alam": 5,
    "uranium": 0,
    "garam": 2
  },
  {
    "country": "Suriname",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 20,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Uruguay",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Venezuela",
    "nikel": 2,
    "bijah_besi": 5,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 5,
    "tembaga": 0,
    "batu_bara": 2,
    "minyak_bumi": 150,
    "gas_alam": 20,
    "uranium": 0,
    "garam": 2
  },
  {
    "country": "Australia",
    "nikel": 40,
    "bijah_besi": 90,
    "litium": 30,
    "logam_tanah_jarang": 6,
    "aluminium": 105,
    "tembaga": 25,
    "batu_bara": 60,
    "minyak_bumi": 10,
    "gas_alam": 55,
    "uranium": 50,
    "garam": 70
  },
  {
    "country": "Fiji",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Guam",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Kiribati",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Marshall",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Mikronesia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Nauru",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Palau",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Papua nugini",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 1,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Samoa",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Samoa amerika",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Selandia baru",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 1,
    "minyak_bumi": 1,
    "gas_alam": 2,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Tahiti",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Tuvalu",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Tonga",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Vanuatu",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 1
  },
  {
    "country": "Togo",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 0,
    "gas_alam": 0,
    "uranium": 0,
    "garam": 0
  },
  {
    "country": "Tunisia",
    "nikel": 0,
    "bijah_besi": 0,
    "litium": 0,
    "logam_tanah_jarang": 0,
    "aluminium": 0,
    "tembaga": 0,
    "batu_bara": 0,
    "minyak_bumi": 1,
    "gas_alam": 1,
    "uranium": 0,
    "garam": 1
  }
];

// Normalize country name untuk matching
function normalizeCountryName(name) {
  return name
    .toLowerCase()
    .replace(/\s+/g, '_')
    .replace(/[àáâãäå]/g, 'a')
    .replace(/[èéêë]/g, 'e')
    .replace(/[ìíîï]/g, 'i')
    .replace(/[òóôõö]/g, 'o')
    .replace(/[ùúûü]/g, 'u');
}

// Create mapping dari country name ke mineral values
const mineralMap = {};
mineralData.forEach(item => {
  const normalized = normalizeCountryName(item.country);
  mineralMap[normalized] = item;
});

const root = path.join(process.cwd(), 'json', 'semua_fitur_negara', '1_pembangunan', '1_produksi', '2_sektor_mineral_kritis');

const regions = ['asia', 'eropa', 'afrika', 'na', 'oceania', 'sa'];
let totalUpdated = 0;
const updateLog = [];
const notFound = [];

const allMinerals = ['nikel', 'bijah_besi', 'litium', 'logam_tanah_jarang', 'aluminium', 'tembaga', 'batu_bara', 'minyak_bumi', 'gas_alam', 'uranium', 'garam'];

// Process each region
regions.forEach(region => {
  const regionPath = path.join(root, region);
  
  if (!fs.existsSync(regionPath)) return;
  
  const files = fs.readdirSync(regionPath).filter(f => f.endsWith('.ts') && f !== '2_db_ekstraksi.ts');
  
  files.forEach(file => {
    const filePath = path.join(regionPath, file);
    
    // Extract country name from filename
    const match = file.match(/^\d+_(.+)\.ts$/);
    if (!match) return;
    
    const countryNameFromFile = match[1];
    const normalizedFileName = normalizeCountryName(countryNameFromFile);
    
    // Look for matching mineral data
    let mineralData = null;
    
    // Try direct match first
    if (mineralMap[normalizedFileName]) {
      mineralData = mineralMap[normalizedFileName];
    } else {
      // Try to find close match
      for (const [key, value] of Object.entries(mineralMap)) {
        if (key.includes(normalizedFileName) || normalizedFileName.includes(key)) {
          mineralData = value;
          break;
        }
      }
    }
    
    if (mineralData === null) {
      notFound.push(`${region}/${file} (${countryNameFromFile})`);
      return;
    }
    
    // Read file and update minerals (excluding emas)
    let content = fs.readFileSync(filePath, 'utf8');
    let modified = false;
    let changeSummary = [];
    
    allMinerals.forEach(mineral => {
      const newValue = mineralData[mineral];
      if (newValue !== undefined) {
        // Build regex to match: mineral: <number>,
        const regex = new RegExp(`(\\s+${mineral}:\\s*)(\\d+)(,)`, 'g');
        const oldMatch = content.match(regex);
        
        if (oldMatch) {
          const oldValue = oldMatch[0].match(/\d+/)[0];
          content = content.replace(regex, `$1${newValue}$3`);
          modified = true;
          
          if (oldValue !== String(newValue)) {
            changeSummary.push({
              mineral,
              old: parseInt(oldValue, 10),
              new: newValue
            });
          }
        }
      }
    });
    
    if (modified) {
      fs.writeFileSync(filePath, content, 'utf8');
      totalUpdated++;
      
      updateLog.push({
        file: `${region}/${file}`,
        country: countryNameFromFile,
        changes: changeSummary
      });
    }
  });
});

console.log('\n' + '='.repeat(80));
console.log('MINERAL DATA UPDATE REPORT');
console.log('='.repeat(80));
console.log(`\nTotal files updated: ${totalUpdated}`);

if (updateLog.length > 0) {
  console.log('\nDetailed changes (summary):');
  updateLog.forEach((log, idx) => {
    console.log(`${String(idx + 1).padStart(3)}. [${log.file}]`);
    if (log.changes.length > 0) {
      log.changes.forEach(change => {
        console.log(`    - ${change.mineral}: ${change.old} → ${change.new}`);
      });
    } else {
      console.log(`    - (values already match)`);
    }
  });
}

if (notFound.length > 0) {
  console.log(`\n⚠️  Not found in mineral data (${notFound.length} files):`);
  notFound.forEach(n => console.log(`   - ${n}`));
}

// Save detailed log
fs.writeFileSync(
  path.join(process.cwd(), 'tools', 'minerals_update_log.json'),
  JSON.stringify({ totalUpdated, updateLog, notFound }, null, 2)
);

console.log(`\nDetailed log saved to: tools/minerals_update_log.json`);
console.log('='.repeat(80) + '\n');
